export default {
  // This is ENGLISH language specific constant file
  // Organization Structure Page
  LOGIN: 'Sign In',
  USER_NAME: 'Username',
  PASSWORD: 'Password',
  ORG_STRUCTURE_SUB_HEADING: ' Organization Structure',
  NO_OF_SUB_ORGS_LABEL: 'Number of Blocks',
  NO_OF_ADMINS_LABEL: 'Number of Admins',
  NO_OF_USERS_LABEL: 'Number of Learners',

  // Start common labels
  REPORT_PAGE_TITLE: 'Reports',
  REQUIRED_FIELD: '*',
  FIRST_NAME: 'First Name',
  MIDDLE_NAME: 'Middle Name',
  LAST_NAME: 'Last Name',
  MOBILE_NUMBER: 'Mobile Number',
  PARENTS_MOBILE_NUMBER: 'Parent\'s Mobile Number',
  MOBILE_NO_REGISTERED: 'Mobile Number already registered.',
  EMAIL_ID: 'Email Id',
  EMAIL_REGISTERED: 'Email Id already registered.',
  SAVE_CHANGES: 'Save Changes',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  IS_REQUIRED: ' is required.',
  DATE: 'Date',
  ALL: 'All',
  A_Z: 'A-Z',
  Z_A: 'Z-A',
  READ: 'Read',
  UNREAD: 'Unread',
  FILTER_BY_LABEL: 'Filter By',
  // ENd common labels

  // Start viewadmins page labels
  VIEW_ORGANIZATION_ADMINS: 'View Organization Admins',
  SEARCH_ADMIN_BY_NAME: 'Search Admin By Name',
  NO_ADMIN_ACCOUNT_FOUND: 'No Admin account found',
  ADMINS: 'Admins',
  ADMIN_NAME: 'Admin Name',
  CENTER_OR_SITE: 'Block',
  ROLE: 'Role',
  CLICK_ADMINNAME_TO_EDIT: '*Click on admin name to edit',
  CREATE_ADMIN_ACCOUNT: 'Create Admin Account',
  // End viewadmins page labels

  // Start createadmin page labels
  CREATE_ADMIN: 'Create Admin',
  EDIT_ADMIN: 'Edit Admin',
  SELECT_ROLES: 'Select Roles',
  // End createadmin page labels

  VIEW_ORGANIZATION_CENTERS: 'View Organization Blocks',
  SEARCH_CENTERS: 'Search Blocks',
  NO_CENTERS_FOUND: 'No Blocks found',
  CENTERS: 'Blocks',
  CENTERS_OR_SITES: 'Blocks',
  DATE_CREATED: 'Date Created',
  CLICK_ON_SITES_TO_EDIT: 'Click on Blocks to edit',
  CREATE_CENTERS_SITES: 'Create Blocks',
  // const for /user/certificates page starts
  CERTIFICATE_HEADING: 'Certificates',
  CERTIFICATE_NAME_LABEL: 'Certificate Name *',
  CERTIFICATE_NAME_PLACEHOLDER: 'Certificate Name',
  CERTIFICATE_AWARDED_BY_LABEL: 'Awarded by/Organisation *',
  CERTIFICATE_AWARDED_BY_PLACEHOLDER: 'Organization Name',
  CERTIFICATE_DATE_RECEIVED_LABEL: 'Date Received *',
  CERTIFICATE_DATE_RECEIVED_PLACEHOLDER: 'DD/MM/YYYY',
  CERTIFICATE_UPLOAD_CERTIFICATE_BUTTON: 'Upload Certificate *',
  CERTIFICATE_ADD_OR_EDIT_BUTTON: 'Add/Edit Certificate',
  CERTIFICATE_ADDING_CERTIFICATE_BUTTON: 'Adding Certificate',
  CERTIFICATE_UPLOADING_CERTIFICATE_BUTTON: 'Uploading Certificate',
  CERTIFICATE_CANCEL_BUTTON: 'Cancel',
  CERTIFICATE_TABLE_CERTIFICATE_NAME_HEADING: 'Certificate Name',
  CERTIFICATE_TABLE_AVARDED_BY_HEADING: 'Awarded by/Organization Name',
  CERTIFICATE_TABLE_RECEIVED_DATE_HEADING: 'Received Date',
  CERTIFICATE_VIEW_BUTTON: 'View Certificate',
  CERTIFICATE_TABLE_INFO: '* Click on the certificate name to edit',
  // const for /user/certificates page ends
  // const for /passwordchange page starts
  CHANGE_PASSWORD_HEADING: 'CHANGE PASSWORD',
  CHANGE_PASSWORD_OLD_PASSWORD_LABEL: 'Old Password *',
  CHANGE_PASSWORD_OLD_PASSWORD_PLACEHOLDER: 'Old Password',
  CHANGE_PASSWORD_NEW_PASSWORD_LABEL: 'New Password *',
  CHANGE_PASSWORD_NEW_PASSWORD_PLACEHOLDER: 'New Password',
  CHANGE_PASSWORD_CONFIRM_PASSWORD_LABEL: 'Confirm Password *',
  CHANGE_PASSWORD_CONFIRM_PASSWORD_PLACEHOLDER: 'Confirm Password',
  CHANGE_PASSWORD_SUBMIT_BUTTON: 'Submit',
  // const for /passwordchange page ends

  // Edit user and upload user data
  EMAIL: 'Email',
  SITES: 'Blocks',
  COURSES: 'Courses',
  SERCH_FOR_COURSE: 'Search for the course..',
  UPLOAD_USER_DATA: 'Upload Learner Data',
  CENTER: 'Block',
  SELECT_CENTER: 'Select Block',
  ASYNC_FIELD: 'Async field',
  FILE_NAME: 'File Name',
  FILE_SELECTION: 'File selection',
  DOWNLOAD_EXCEL_TEMPLATE: 'Download Excel Template',
  UPLOAD_DIRTY_MSG: ' is required.',
  UPLOAD_FILE: 'Upload File',
  SEAT_AVAILABLE: 'Seat Available',
  STUDENT_SELECTED: 'Student Selected',
  STUDENT: 'Student',
  CREATE_USER: 'Create Learner',
  EDIT_USER_ACCOUNT: 'Edit Learner Account',
  SELECT_FILE: 'Select File',
  LEARNER_DETAILS: 'Learner Details',
  LICENSE_NUMBER: 'License Number',
  ENRROLLED_END_DATE: 'License End Date',
  LICENSE_STATUS: 'License Status',
  ENROLLED_DATE: 'Enrolled Date',
  SEARCH_COURSES: 'Search Courses',
  CREATE_USER_ACCOUNT: 'Create Individual Learner Account',
  ENROLLED_TO_OTHER_ORG_SUBTITLE_MSG: 'Note:Please enroll with different emailIds other then listed below',
  UNABLE_TO_UPLOAD_BULK_USER_FILE: 'Unable to upload file.Please select valid file format',
  USER_ENROLLED_TO_COURSE_SUBTITLE_MSG: 'Note:Please Remove below listed user to proceed with enrollment',
  INSUFFICIENT_LICENSE_SUBTITLE_MSG:
    'Note:Please select course with valid number of available seats or Remove some of the students',
  UPLOAD_LEARNERS: 'Upload Learners',

  // Create Site
  CREATE_ORGANISATION_CENTER: 'Create Organization Block',
  EDIT_ORGANISATION_CENTER: 'Edit Organization Block',
  CENTER_NAME: 'Block Name',
  CITY: 'City',
  CENTER_ADMINS: 'Block Admins',
  SELECT_ADMIN: 'Select Admin',
  CREATE_CENTER: 'Create Block',
  MY_INFO: 'My Info',
  BASIC_INFORMATION: 'Basic Information',
  MOBILE_NO: 'Mobile No ',
  GENDER: 'Gender',
  DOB: 'Date Of Birth',
  ADDRESS: 'Address',
  MARITAL_STATUS: 'Marital Status',
  ADDRESS_LINE_1: 'Address Line 1',
  ADDRESS_LINE_2: 'Address Line 2',
  ENTER_ADDRESS_LINE_1: 'Enter Address Line 1',
  ENTER_ADDRESS_LINE_2: 'Enter Address Line 2',
  ENTER_CITY: 'Enter City',
  STATE: 'State',
  ENTER_STATE: 'Enter State',
  COUNTRY: 'Country',
  ENTER_COUNTRY: 'Enter Country',
  PINCODE: 'Pincode',
  ENTER_PINCODE: 'Enter Pincode',

  // for forgot password localization
  RESET_PASSWORD: 'RESET PASSWORD',
  EMAIL_ADDRESS: 'E-Mail Address',
  OR: 'Or',
  TEMPORARY_PASSWORD_MSG: 'How would you like to receive your temporary password?',
  SEND: 'Send',
  TEMPORARY_SMS_SUCCESS_MSG:
    'A SMS with your temporary password has been sent to the mobile phone number on your profile.',
  TEMPORARY_MAIL_SUCCESS_MSG: 'A temporary password has been sent to the e-mail address on your profile.',
  TEMPORARY_LOGIN_MSG: 'Login with your learner id and temporary password.',
  RESEND_TEMPORARY_PASSWORD_LINK: 'Resend Temporary Password',
  // end forgot password page
  // COURSE OVERVIEW PAGE
  COURSE_OVERVIEW_BY: 'By',
  COURSE_OVERVIEW_LANGUAGE: 'Language',
  COURSE_OVERVIEW_PREVIEW_COURSE: 'Preview Course',
  COURSE_OVERVIEW_TAKE_ASSESSMENT: 'Take Assessment',
  COURSE_OVERVIEW_ENTER_CLASSROOM: 'Enter Classroom',
  COURSE_OVERVIEW_VIEW_ALL_COURSE: 'View All Course',
  COURSE_OVERVIEW_COURSE_OUTLINE: 'Course Outline',
  COURSE_OVERVIEW_OUTCOME: 'Outcome',
  COURSE_OVERVIEW_LEVEL: 'Level',
  COURSE_OVERVIEW_PRE_REQUESTIES: 'Pre-Requesties',
  COURSE_OVERVIEW_DURATION: 'Duration',
  COURSE_OVERVIEW_WHO_SHOULD_ATTEND: 'Who should attend',
  COURSE_OVERVIEW_JOB_ROLE: 'Job Role',
  COURSE_OVERVIEW_INDUSTRY: 'Industry',
  COURSE_OVERVIEW_PRICE: 'Price',
  COURSE_OVERVIEW_RESOURCES: 'Course Resource',
  // END COURSE OVERVIEW
  // CLASSROOM PAGE
  CLASSROOM_OBJECTIVE: 'Learning outcome',
  CLASSROOM_SEARCH_PLACEHOLDER: 'Search for...',
  CLASSROOM_COURSE_DETAILS: 'Course Details',
  // END CLASSROOM
  // Roles page(view Roles)
  VIEW_ROLES: 'View Roles',
  ROLES: 'Roles',
  SEARCH_ROLE: 'Search Role',
  ROLE_NAME: 'Role Name',
  ROLE_TYPE: 'Role Type',
  CREATED_ON: 'Created On',
  START_DATE: 'Start Date *',
  END_DATE: 'End Date *',
  STATUS: 'Status',
  VIEW_ROLE_NAME_INFO: '*Click on the role name to edit.',
  VIEW_ROLE_DATE_INFO: '*Start and end dates are for temporary roles.',
  NO_ROLES_AVAILABLE: 'No Roles are available',
  // END View Roles
  // ASSESMENT LOCAlIZATION
  ASSESSMENT_START_TEST: 'Start Test',
  ASSESSMENT_NO_OF_QUESTION: 'No of question',
  ASSESSMENT_NO_OF_ATTEMPTS: 'No of attempts',
  ASSESSMENT_TOTAL_MARKS: 'Total Marks',
  ASSESSMENT_PASSING_MARKS: 'Passing Marks',
  ASSESSMENT_DURATION: 'Duration',
  ASSESSMENT_PREV_QUESTION: 'Previous Question',
  ASSESSMENT_NEXT_QUESTION: 'Next Question',
  ASSESSMENT_SUBMIT_TEST: 'Submit Test',
  ASSESSMENT_SL_NO: 'Sl. No.',
  ASSESSMENT_YOUR_SCORE: 'Your Score',
  ASSESSMENT_YOUR_MARKS: 'Your Marks',
  ASSESSMENT_DATE: 'Date',
  ASSESSMENT_TEST_STATUS: 'Status',
  ASSESSMENT_RESULT: 'Result',
  ASSESSMENT_PASS_MARKS: 'Pass Marks',
  ASSESSMENT_GO_TO_CHAPTER: 'Go to chapter',
  ASSESSMENT_RETEST: 'Retest',
  ASSESSMENT_GO_TO_CERTIFICATES: 'Go to my certificates',
  ASSESSMENT_CONFIRM_SUBMIT: 'Do you want to submit the test',
  ASSESSMENT_ANSWER_ALL: 'Answer all the question, before submiting the test',
  ASSESSMENT_SUBMIT_TITLE: 'Submit Test',
  ASSESSMENT_SUBMIT_BUTTON: 'Submit',
  ASSESSMENT_PASS: 'You have successfully completed this chapter.',
  ASSESSMENT_CERTIFICATE_PASS: 'You have successfully completed this course.',
  ASSESSMENT_FAIL: 'Please study the chapter carefully again.',
  ASSESSMENT_FINAL_FAIL: 'Please study the below chapters carefully again.',
  ASSESSMENT_RECOMMENDATION: ' You can study the following chapters to obtain better score.',
  ASSESSMENT_SELECT_ANSWER: 'Select an answer',
  ASSESSMENT_LABEL_PASS: 'PASS',
  ASSESSMENT_LABEL_FAIL: 'FAIL',
  ASSESSMENT_GRADE: 'Grade',
  // END ASSESSMENT
  // Forum Page
  CATEGORIES: 'Categories',
  SEARCH_CATEGORIES_LABEL: 'Search Categories',
  SEARCH_TOPICS_LABEL: 'Search Topics',
  TOPICS: 'Topics',
  CATEGORY_SELECT_LABEL: 'Please Select a Category',
  POST: 'Posts',
  TOPIC_SELECT_LABEL: 'Please Select a Topic',
  NO_CATEGORIES_LABEL: 'No Categories Yet',
  NO_TOPICS_LABEL: 'No Categories',
  SEARCH_POSTS: 'Search Within Selected Topic',
  SORT_BY_LABEL: 'Sort By',
  RECENT_LABEL: 'Recent',
  NO_POSTS_LABEL: 'No Posts',
  START_DISCUSSION_LABEL: 'Start Discussion',
  TRENDING_DISCUSSION_LABEL: 'Trending Discussions',
  NO_DICUSSION_LABEL: 'No Trending Discussion',
  LOGIN_TO_VOTE: 'Please login to vote.',
  LOGIN_TO_COMMENT: 'Please login to comment.',
  LOGIN_TO_POST: 'Please log in to post discussion.',
  // Role Default
  ORGANIZATION_ROLE_OVERVIEW_LABEL: 'Organization Role Overview',
  ORGANIZATION_NAME_LABEL: 'Organization Name',
  NO_OF_ROLES_LABEL: 'Number Of Roles',
  // Login page
  FORGOT_PASSWORD: 'Forgot Password?',
  USERNAME_PLACEHOLDER: 'Login ID / email address',
  INVALID_CREDENTIALS: 'Invalid credentials',
  // Course catalog page
  VIEW_ALL_COURSES_LINK: 'View all courses',
  VIEW_ALL_CATEGORIES_LINK: 'View all Categories',
  PARTICIPATE_IN_DISCUSSION_LINK: 'Participate in Discussion',
  COURSE_CAROUSEL_WHAT_WOULD_YOU_LIKE_TO: 'What would you like to',
  COURSE_CAROUSEL_TODAY: 'today?',
  HOST_TYPE_VOCATIONAL_DESCRIPTION: `A uniquely positioned technology company that blends engineering and manufacturing knowledge to
  develop self-directed, digitally interactive products, simulating real life experiences. Knowledge Podium
  creates comprehensive & simplistic products to assimilate, institutionalise, distribute and assure consumption
  of an organisation’s knowledge across its value-chain. The organisation has successfully created products for
  engineering, manufacturing, skill up-gradation and knowledge retention needs of major industries and large
  educational institutions in India and abroad.`,
  HOST_TYPE_TEACHERS_DESCRIPTION: `We believe in transformation and hence providing an opportunity to anyone, anywhere by accessing
  world’s best learning experience. You can choose from the list of courses, the one that helps you earn specialisation
  in the area of interest. So let your time and space challenges disappear, and you take your learning journey forward.
  Choose what you want to learn today.`,
  COURSE_CAROUSEL_LEARN: ' LEARN ',
  // Footer
  CONTACT: 'Contact',
  QUICK_LINKS: 'Quick Links',
  ABOUT_US: 'About Us',
  TERMS_OF_USE: 'Terms of Use',
  PRIVACY_POLICY: 'Privacy Policy',
  CONTACT_US: 'Contact Us',
  FAQ: 'FAQs',
  HOW_TO: 'How To?',
  HAVE_A_QUESTION: 'Have a Question?',
  LEAVE_A_REPLY_MESSAGE: 'Leave your email id below. We will get in touch with you.',
  EMAIL_PLACEHOLDER: 'Enter Email ID',
  SELECT_LANGUAGE: 'Select Language',

  // Roles
  ROLE_START_DATE_LABEL: 'Role Start Date (If temp.)',
  ROLE_END_DATE_LABEL: 'Role End Date (If temp.)',
  NEXT: 'Next',
  DELETE: 'Delete',
  DELETE_ROLE: 'Delete Role',
  ROLE_NAME_PLACEHOLDER: 'Enter role name',
  ROLE_TYPE_PLACEHOLDER: 'Select role type',
  CREATE_ROLE_LABEL: 'Create Role',
  EDIT_RESPONSIBILITIES_LABEL: 'Edit Responsibility',
  DELETE_ROLE_TITLE: 'Delete Role Confirmation',
  ROLE_DELETE_ALERT_LABEL: 'Are you sure you want to delete this role?',
  ROLE_IN_USER_LABEL: 'Role is in use.Please change the roles for the following admins and try again.',
  EDIT_ROLE: 'Edit Role',
  REGULAR_LABEL: 'Regular',
  TEMPORARY_LABEL: 'Temporary',
  //  Admin Licesne Page Labels
  ADMIN_LICENSE_LABEL_LICENSES: 'Licenses',
  ADMIN_LICENSE_SEARCH_LICENSE_PLACE_HOLDER: 'Search course Licenses',
  ADMIN_LICENSE_LICENSE_ID: 'License Id',
  ADMIN_LICENSE_COURSE_PRODUCT_NAME: 'Course / Product name',
  ADMIN_LICENSE_PURCHASE_DATE: 'Purchase Date',
  ADMIN_LICENSE_QUANTITY: 'Quantity',
  ADMIN_LICENSE_LICENSE_REMAINING: 'License Remaining',
  ADMIN_LICENSE_STATUS: 'Status',
  ADMIN_LICENSE_LICENESE_VIEW_NOTE: '*Click on course name to view license details',
  //  Admin License Details Page Labels
  ADMIN_LICENSE_DETAILS_LABEL_LICENSE_DETAILS: 'License Details',
  ADMIN_LICENSE_DETAILS_PRODUCT_NAME: 'Product Name',
  ADMIN_LICENSE_DETAILS_REQUEST_DATE: 'Requested Date',
  ADMIN_LICENSE_DETAILS_START_DATE: 'Start Date',
  ADMIN_LICENSE_DETAILS_END_DATE: 'End Date',
  ADMIN_LICENSE_DETAILS_LICENSE_PURCHASED: 'License Purchased',
  ADMIN_LICENSE_DETAILS_LICENSE_USED: 'License Used',
  ADMIN_LICENSE_DETAILS_REQUEST_MORE_LICENSE_LABEL: 'Request More License',
  ADMIN_LICENSE_DETAILS_SEARCH_ADMIN: 'Search Admin',
  ADMIN_LICENSE_DETAILS_ADMIN_LICENSE_USER_NAME: 'Learner Name',
  ADMIN_LICENSE_DETAILS_USER_EMAIL_ID: 'Learner EmailId',
  ADMIN_LICENSE_DETAILS_ENROLLED_DATE: 'Enrolled Date',
  ADMIN_LICENSE_DETAILS_USER_PROGRESS: 'Progress',

  // Dashboard
  DASHBOARD_RECENTLY_VIEWED: 'RECENTLY VIEWED',
  DASHBOARD_MY_COURSES: 'MY COURSES',
  DASHBOARD_RECOMMENDED_COURSES: 'RECOMMENDED COURSES',
  DASHBOARD_COURSES_PROGRESS: 'Progress',
  DASHBOARD_CREATED_BY: 'Created by',
  DASHBOARD_POD: 'POD:',
  VIEW_ALL: 'View All',
  TAKE_ASSESSMENT: 'Take Assessment',
  ENTER_CLASSROOM: 'Enter Classroom',
  PREVIEW_COURSE: 'Preview',
  NO_SUBSCRIPTION: 'No Current Subscriptions to Display',
  CURRENT_SUBSCRIPTION: 'Current Subscriptions',
  COURSE_NAME: 'Course Name',
  COURSE_PROGRESS: 'Course Progress',
  SUBSCRIPTION_LEFT: 'Subscription Days Left',
  NO_PAST_SUBSCRIPTION: 'No Past Subscriptions to Display',
  PAST_SUBSCRIPTION: 'Past Subscriptions',
  EXPIRED_DATE: 'Expired Date',
  NOT_PERMITTED: 'Not Permitted.',
  COURSE_LEVEL: 'Course Level ',

  // discussion
  DISCUSSION_FORUMS_FIELD: 'Forums*',
  DISCUSSION_FORUM_LABEL: 'Type Forum name',
  DISCUSSION_TOPIC_FIELD: 'Select topic*',
  DISCUSSION_TOPIC_LABEL: 'Type Topic name',
  DISCUSSION_LEVEL_FIELD: 'What best defines the "level" of your topic?*',
  DISCUSSION_TITLE_FIELD: 'Title*',
  DISCUSSION_TITLE_LABEL: 'Enter title here',
  DISCUSSION_DESCRIPTION_FIELD: 'Your post/comment here*',
  DISCUSSION_REQUIRED: 'Description * is required.',
  POST_DISCUSSION: 'Post Discussion',
  PREVIEW_DISCUSSION: 'Preview',
  EDIT_DISCUSSION: 'Edit',
  DISCUSSION_POST: 'Post',
  // REQUIRED_COMMENT: 'Comment is required.',
  REPLY_COMMENT: 'Reply',
  COMMENT_FLAG: 'Flag',
  DISCUSSION_COMMENTS: 'Comments',
  ADD_COMMENT: 'Add Comment',

  // OrgAdminRequests
  REQUEST_TYPE: 'Request Type*',
  REQUEST_DETAILS: 'Request Details*',
  SELECT_REQUEST_TYPE: 'select request type',
  SEARCH_COURSE: 'Search for the course..',
  REQUEST_DETAILS_PLACEHOLDER:
    'Briefly describe your request and one of our customer representatives will reply within 24 hours.',
  ORG_ADMIN_REQUESTS_SUBMIT: 'Submit',
  ORG_ADMIN_REQUESTS_HEADING: 'Please tell us how we may help you',
  ORG_ADMIN_REQUESTS_SUBHEADING: '*For immediate help with technical problems please call our sales representative.',
  // My Certificate
  MYCERTIFICATE_HEADING: 'MY CERTIFICATES',
  NO_CERTIFICATE: 'No Certificates found.',
  VIEW_CERTIFICATE: 'View Certificate',
  // Modal
  MODAL_OK: 'Ok',
  MODAL_CANCEL: 'Cancel',
  // End Modal

  // view Users
  NUMBER_OF_ENROLLED_PODS: 'No. Enrolled pods',
  NUMBER_OF_COMPLETED_PODS: 'No. Completed pods',
  CLICK_ON_USER_NAME_TO_EDIT: 'Click on learner name to edit',
  SEARCH_USERS: 'Search Learners',
  LEARNER_NAME: 'Learner Name',

  // <-- url: /admin/detail,  Admin Detail page localization start -->
  ADMIN_ACCOUNT_DETAILS: 'Admin Account Details',
  ORGASNISATION_NAME: 'Organisation Name',
  ADMIN_FIRST_NAME: 'Admin First Name',
  ADMIN_LAST_NAME: 'Admin Last Name',
  ADMIN_EAIL_ID: 'Admin Email ID',
  ADMIN_MOBILE_NO: 'Admin Mobile No',
  ADMIN_CONTACT_US_PLEASE: 'Please',
  ADMIN_CONTACT_US_UPDATE: 'to modify or update account details',
  ADMIN_CONTACT_US: 'contact us',

  // <-- url: /admin/detail,  Admin Detail page localization end -->
  // Admin home screen welcme message
  ADMIN_ROUTEPAGE_WELCOME: 'Welcome',
  ADMIN_ROUTEPAGE_ADMINISTRATOR: 'Administrator',
  SEE_COURSE_DETAILS: 'See course details',

  MY_COURSES: 'MY COURSES',
  SORT_BY: 'List By',
  NO_RECORDS_FOUND: 'No records found',
  // EDUCATION_QUALIFICATIONS
  EDUCATION_QUALIFICATIONS: 'Education Qualifications',
  LEVEL_OF_EDUCATION: 'Level of Education',
  INSTITUTION_NAME: 'Institution name',
  FIELD_OF_STUDY: 'Field of Study',
  PERCENTAGE: 'Percentage',
  YEAR_OF_GRADUATION: 'Year of Graduation',
  CURRENTLY_PURSUING: 'Currently pursuing',
  SELECT_EDUCATION: 'Select Education',
  SAVE_EDUCATION: 'Save Education',
  ADD_EDUCATION: 'Add Education',
  NAME_OF_THE_INSTITUTION: 'Name of the institution',
  EDUCATION_DELETE_ALERT_LABEL: 'Are you sure you want to delete this education?',
  DELETE_EDUCATION_CONFIRMATION: 'Delete Education Confirmation',

  RECOMMENDED_COURSES: 'RECOMMENDED COURSES',
  WORK_EXPERIENCE: 'Work Experience',
  DELETE_WORK_EXPERIENCE_CONFIRMATION: 'Delete Work Experience Confirmation',
  WORK_EXPERIENCE_DELETE_ALERT_LABEL: 'Are you sure you want to delete this work experience?',
  JOB_TITLE: 'Job Title *',
  ORG: 'Organisation *',
  START_MONTH: 'Start Month',
  START_YEAR: 'Start Year',
  END_MONTH: 'End Month',
  END_YEAR: 'End Year',
  CURRENTLY_WORKING: 'Currently Working',
  JOB_DESC: 'Job Description',
  TO: 'to',
  ENTER_JOB_TITLE: 'Enter Job Title',
  ENTER_ORG_NAME: 'Enter Organisation name',
  MONTH: 'Month',
  YEAR: 'Year',
  JOB_RESP_ACHIVEMENTS: 'List job responsibilties and achievements',
  UPDATE_JOB: 'Update Job',
  ADD_JOB: 'Add Job',
  MY_SKILLS: 'MY SKILLS',
  SKILLS: 'Skills',
  SKILL: 'Skill',
  YEARS: 'Years',
  EXPERIENCE: 'Experience',
  MONTHS: 'Months',
  UPDATE_SKILL: 'Update Skill',
  ADD_SKILL: 'Add Skill',
  TYPE_SKILL_NAME: 'Type skill name',
  // Recommended Courses
  RECOMMENDED_CHAPTER_NAME: 'Chapter',
  RECOMMENDED_WRONG_ANSWER_COUNT: 'No Of Wrong Answers',

  // user inbox constants
  NO_RESULTS_TO_SHOW: 'No more results to show.',
  NO_CONVERSATIONS: 'No conversations to display.',
  NO_ACTIVE_CONVERSATION: 'No active conversation to display.',
  CREATE_CONVERSATION: 'Start new conversation',
  DELETE_CONVERSATION: 'Delete selected conversation',
  ADD_CONNECTION: 'Add Connection',
  BLOCK_CONNECTION: 'Block Connection',
  UNBLOCK_CONNECTION: 'Unblock Connection',
  CONVERSATION_DELETE_ALERT_LABEL: 'Are you sure you want to delete the selected conversation?',
  DELETE_CONVERSATION_LABEL: 'Delete selected conversation confirmation',
  SEARCH_CONNECTION_LABEL: 'Search Connection',
  CONNECT_LABEL: 'Connect',
  NO_PREVIOUS_CONVERSATION: 'No previous conversation to display',
  TYPE_NAME: 'Type a name',
  ADD_CONNECTION_PLACEHOLDER: 'Enter email id of the user you want to add',
  DELETE_USER: 'Delete User',
  DELETE_LEARNER: 'Delete Learner',
  ACCEPT_INVITATION_LABEL: 'Accept Invitation',
  // REJECT_LABEL: 'Deny',
  REJECT_LABEL: 'Reject',
  DELETE_LABEL: 'Delete',
  PENDING_INVITATION_COUNT: 'Pending invitation count',
  SEND_ADD_REQUEST_LABEL: 'Send Add Request',
  EDIT_ADD_SEND_REQUEST_LABEL: 'Edit Message and Send',
  DENY_LABEL: 'Deny',

  // verify email
  PROCEED_BUTTON: 'Proceed',
  RESEND_BUTTON: 'Resend',
  VERIFY_EMAIL_LINK_SUCCESS_MSG:
    'Congratulations, your email has been verified successfully Please click below to login',
  VERIFY_EMAIL_LINK_FAILURE_MSG: 'Sorry, your link has been expired. To resend the link Please click below',
  // end of verify email
  ACCEPT_LABEL: 'Approve',
  ACTIONS: 'Actions',

  // Delete Certificate confirmation
  DELETE_CERTIFICATE_CONFIRMATION: 'Are you sure you want to delete this certificate?',
  DELETE_CONFIRMATION_TITLE: 'Delete Certificate Confirmation',

  APPROVE_LEARNER_CONFIRMATION: 'Are you sure you want to approve the learner?',
  APPROVE_LEARNER_CONFIRMATION_TITLE: 'Learner Confirmation',
  // REJECT_LEARNER_CONFIRMATION: 'Are you sure you want to deny learner request?',
  // REJECT_LEARNER_CONFIRMATION_TITLE: 'Deny Learner Request',
  // DELETE_LEARNER_CONFIRMATION_TITLE: 'Delete Learner',

  DELETE_LEARNER_CONFIRMATION: 'Are you sure you want to delete the learner?',
  DELETE_LEARNER_CONFIRMATION_TITLE: 'Delete Learner Confirmation',
  REJECT_LEARNER_CONFIRMATION: 'Are you sure you want to reject the learner?',
  REJECT_LEARNER_CONFIRMATION_TITLE: 'Reject Learner Confirmation',


  SHOW_ADD_COMMENT_ERROR: 'Comment Required.',

  LOOKING_FOR: 'What are you looking for ?',
  REFINE_SEARCH: 'Refine Search',
  RESET: 'Reset',
  INDUSTRY: 'Industry',
  TYPE: 'Type',
  SKILL_LEVEL: 'Skill Level',
  SELECT: 'Select',
  END_RESULT: 'End Of Results',
  VIEW: 'View',
  COURSES_CATALOG: 'COURSES CATALOG',
  COURSE_DURATION: 'Course Duration:',
  LEARN_MORE: 'Learn More',
  DELETE_SKILL_CONFIRMATION: 'Are you sure you want to delete this skill?',
  DELETE_TITLE_SKILL_CONFIRMATION: 'Delete Skill Confirmation',
  ENTER_CLASSROOM_EXPIRES:
    'Pod license has been expired. To Enter Classroom, Please renew the license / Contact your admin to renew license',
  ENTER_CLASSROOM_RECOMMENDED: 'You can view only 2 links without buying the pod',
  SCHOOL: 'School',
  DISTRICT: 'District',
  // Reports
  REPORT_SEARCH_LABEL: 'Find available reports for a State, District, Block, School or Student',
  REPORT_SEARCH_PLACEHOLDER: 'Enter District, Block, School or Student Name',
  REPORT_ALL_DISTRICTS: 'All Districts',
  REPORT_ALL_BLOCKS: 'All Blocks',
  REPORT_ALL_SCHOOLS: 'All Schools',
  REPORT_SUMMARY_TITLE: 'Teachers Training Program Summary',
  REPORT_DOWNLOAD_LABEL: 'Download Summary',
  REPORT_TOTAL_LEARNERS_LABEL: 'Total Learners',
  REPORT_ACTIVE_COURSES_LABEL: 'Active Courses',
  REPORT_ACTIVE_ENROLLMENTS_LABEL: 'Active Enrollments',
  REPORT_COURSES_INPROGRESS_LABEL: 'Total Inprogress Courses',
  REPORT_CERTIFICATE_AWARDED_LABEL: 'Certificate Awarded',
  REPORT_STATISTICS_AND_ANALYTICS_LABEL: 'Statistics and Analytics',
  REPORT_TOTAL_COURSES_LABEL: 'Total Courses',
  REPORT_TOTAL_STUDENT_LABEL: 'Total Learners',
  REPORT_INPROGRESS_LABEL: 'In progress',
  REPORT_YET_TO_START_LABEL: 'Yet to start',
  REPORT_COMPLETED_LABEL: 'Completed',
  REPORT_ENROLLED_LABEL: 'Active',
  REPORT_INACTIVE_LABEL: 'Inactive',
  REPORT_CERTIFICATE_AWARDED_TITLE: 'Certificate awarded vs courses',
  REPORT_STUDENT_VS_COURSES_TITLE: 'Learners vs Available Courses',
  REPORT_DISTRICTS_DIRECTORY_LABEL: 'Districts Directory',
  REPORT_STATE_LABEL: 'state:',
  REPORT_KARNATAKA: 'Karnataka',
  REPORT_VIEW_REPORTS_LABEL: 'View Reports',
  REPORT_DISTRICT_NAME_HEADING: 'District Name',
  REPORT_BLOCKS_HEADING: 'Blocks',
  REPORT_HEADING: 'Report',
  REPORT_FIND: 'Find the ',
  REPORT_VIEW_ALL: 'View All',
  REPORT_BLOCK_NAME_HEADING: 'Block Name',
  REPORT_SCHOOLS_HEADING: 'Schools',
  REPORT_SCHOOL_NAME_HEADING: 'School Name',
  REPORT_DISTRICT_LEVEL: 'District',
  REPORT_BLOCK_LEVEL: 'Block',
  REPORT_SCHOOL_LEVEL: 'School',
  // End Reports
  COURSE_RESOURCE: 'Resources',
  MAX_LENGTH_EXCEEDED: 'Max length exceeded!!',
  // Contact
  KP_CONTACTDETAILS_LINE_1: '21, Sidcul IT Park, Sahastradhara',
  KP_CONTACTDETAILS_LINE_2: 'Road, Dehradun - 248001,',
  KP_CONTACTDETAILS_STATE: 'Uttarakhand,',
  KP_CONTACTDETAILS_COUNTRY: 'India',
  KP_CONTACTDETAILS_PHONE_NUMBER: 'P: +91 97564 31011',
  KP_CONTACTDETAILS_EMAILID: 'E: contact@knowledgepodium.com',

  // USER BASIC INFO
  SCHOOLDETAILS: 'School Information',
  BLOCK: 'Block',
  // SCHOOL: 'School',

  // SELF_REGISTRATION
  SELF_REGISTRATION: 'Self Registration',
  SIGN_UP: 'Sign Up',
  CONTINUE: 'Verify Mobile Number',
  EDIT_DETAILS: 'Edit Info',
  ACTIVE_USERS: 'Active Users',
  DELETED_USERS: 'Deleted Users',
  PENDING_LIST: 'Pending List',
  TEACHERS_TRAINING_SIGN_UP: 'Teacher Training Registration',
  SUCCESSFULL_REGISTRATION: 'You have been registered successfully!',
  FOLLOW_INSTRUCTIONS: 'Follow the instructions in the email.',
  BASIC_INFO_SCHOOL_INFO: 'Basic Information & School Information',
  // CONTINUE: 'Continue',
  OTP_VERIFY: 'Verify OTP',
  BASIC_INFO: 'Basic Information',
  EDIT_PERMISSION_DENIED: "You don't have the Permission to edit",

  CANCEL_ADD_REQUEST: 'Cancel Add Request',
  FEEDBACK: 'FEEDBACK',
  BEGIN_SURVEY: 'Begin Survey',
  WE_VALUE_YOUR_FEEDBACK: 'We value your feedback',
  DESCRIPTION_FOR_FEEDBACK:
    'The Karnataka State Government would like your feedback on this new Teacher Training Program. Help us improve our platform and other courses offered by taking this survey.',
  ANSWER: 'Answer',
  // Grace Period message for
  GRACE_PERIOD_MESSAGE: 'your license will expire in',
  DAYS: 'days. Please renew the license to continue.',

  // Course Progress Report
  FAILED_TO_FETCH_COURSE_PROCESS: 'Failed to fetch course progress details',
  PROGRESS_COMPLETED_LABEL: 'Completed',
  PROGRESS_INCOMPLETE_LABEL: 'Incomplete',
  PROGRESS_CHAPTERS_LABEL: 'Chapters',
  ASSESSMENT_ATTEMPTED: 'Attempted on',
  ASSESSMENT_SCORE: 'Score',
  UNWATCHED_VIDEOS: 'Unwatched videos',
  COURSE_PROGRESS_REPORT: 'Progress',

  YOUR_FEEDBACK_IS_IMPORTANT_TO_US: 'Your Feedback Is Important To Us',
  LEVEL_OF_EDUCATION_PURSUNING: 'What level of Education are you pursuning?',
  FIRST_STEP: 'Take your first step to getting an',
  EDUCATION_IN_INDIA: 'Education in India',
  REGISTRATION: 'Registration',

  USER_DELETE_ALERT_LABEL: 'Are you sure you want to delete this user?',

  // My Journal DashBoard
  RJ_MY_JOURNAL: 'My Journal',
  RJ_MY_COURSES: 'My Courses',
  NO_POD_AVAILABLE: 'You have not subscribed for any course. Please contact your site admin',
  DOWNLOAD_CHAPTER: 'Download Chapter',
  DOWNLOAD_ALL: 'Download All',
  DOWNLOAD_MODULE: 'Download Module',
  JOURNAL_COMPLETED: 'Completed',
  JOURNAL_RESUME: 'Resume',
  DOWNLOAD_COURSE: 'Download Course',
  DOWNLOAD_JOURNALS: 'Download Journals',
  RJ_SEARCH_JOURNAL: 'Search Journals',
  // End My Journal Dashboard

  POSTS: 'Posts',
  FORUMS: 'Forums',
  SEARCH_FORUMS: 'Search Forums',
  SEARCH_POSTS_NEW: 'Search Posts',
  LAST_POST: 'Last Post',
  HOME: 'Home',

  RESUME_NOW: 'Resume Now',
  RESULTS_FOUND: 'Results Found',

  // contact us new
  PURPOSE_OF_INQUIRY: 'Purpose Of Inquiry',
  NAME: 'Name',
  MOBILE: 'Mobile',
  YOUR_MESSAGE: 'Your message',
  SUBMIT: 'Submit',
  // end of contact us new
  REGISTER: 'Register',
};
