export default {
  // This is HINDI language specific constant file
  LOGIN: 'साइन इन करें',
  USER_NAME: 'उपयोगकर्ता नाम',
  PASSWORD: 'पारण शब्द',
  ORG_STRUCTURE_SUB_HEADING: ' संगठन संरचना',
  NO_OF_SUB_ORGS_LABEL: 'केंद्रों की संख्या',
  NO_OF_ADMINS_LABEL: 'व्यवस्थापक की संख्या',
  NO_OF_USERS_LABEL: 'शिक्षार्थियों की संख्या',

  // Start common labels
  REQUIRED_FIELD: '*',
  FIRST_NAME: 'पहला नाम',
  MIDDLE_NAME: 'मध्य नाम',
  LAST_NAME: 'अंतिम नाम',
  MOBILE_NUMBER: 'मोबाइल नंबर',
  PARENTS_MOBILE_NUMBER: 'माता-पिता का मोबाइल नंबर',
  MOBILE_NO_REGISTERED: 'मोबाइल नंबर पहले से पंजीकृत है.',
  EMAIL_ID: 'ईमेल आईडी',
  EMAIL_REGISTERED: 'ईमेल आईडी पहले से पंजीकृत है.',
  SAVE_CHANGES: 'परिवर्तनों को सुरक्षित करें',
  CANCEL: 'रद्द करना',
  // ENd common labels

  // Start viewadmins page labels
  VIEW_ORGANIZATION_ADMINS: 'संगठन के व्यवस्थापक देखें',
  SEARCH_ADMIN_BY_NAME: 'नाम से व्यवस्थापक खोजें',
  NO_ADMIN_ACCOUNT_FOUND: 'कोई व्यवस्थापक खाता नहीं मिला',
  ADMINS: 'व्यवस्थापक',
  ADMIN_NAME: 'व्यवस्थापक का नाम',
  CENTER_OR_SITE: 'ब्लॉक',
  ROLE: 'भूमिका',
  CLICK_ADMINNAME_TO_EDIT: '*संपादित करने के लिए व्यवस्थापक नाम पर क्लिक करें',
  CREATE_ADMIN_ACCOUNT: 'व्यवस्थापक खाता बनाएँ',
  // End viewadmins page labels

  // Start createadmin page labels
  CREATE_ADMIN: 'व्यवस्थापक बनाएँ',
  EDIT_ADMIN: 'व्यवस्थापक संपादित करें',
  SELECT_ROLES: 'भूमिका का चयन करें',
  // End createadmin page labels

  VIEW_ORGANIZATION_CENTERS: 'संगठन ब्लॉक देखें',
  SEARCH_CENTERS: 'ब्लॉक खोजें',
  NO_CENTERS_FOUND: 'कोई ब्लॉक नहीं मिला',
  CENTERS: 'ब्लाकों',
  CENTERS_OR_SITES: 'ब्लाकों',
  DATE_CREATED: 'निर्माण की तिथि',
  CLICK_ON_SITES_TO_EDIT: 'संपादित करने के लिए ब्लॉक पर क्लिक करें',
  CREATE_CENTERS_SITES: 'ब्लॉक बनाएं',
  // for forgot password localization
  RESET_PASSWORD: 'पासवर्ड रीसेट',
  EMAIL_ADDRESS: 'ईमेल पता',
  OR: 'या',
  TEMPORARY_PASSWORD_MSG: 'आप अपना अस्थायी पासवर्ड कैसे प्राप्त करना चाहेंगे?',
  SEND: 'भेजें',
  TEMPORARY_SMS_SUCCESS_MSG: 'आपके अस्थायी पासवर्ड के साथ एक एसएमएस आपके प्रोफ़ाइल के मोबाइल फोन नंबर पर भेजा गया है।',
  TEMPORARY_MAIL_SUCCESS_MSG: 'आपकी प्रोफ़ाइल पर उल्लिखित ई-मेल आईडी पर एक अस्थायी पासवर्ड भेजा गया है।',
  TEMPORARY_LOGIN_MSG: 'अपने शिक्षार्थी आईडी और अस्थायी पासवर्ड के साथ लॉगिन करें।',
  RESEND_TEMPORARY_PASSWORD_LINK: 'अस्थायी पासवर्ड को फिर से भेजें',
  // end forgot password page
  // COURSE OVERVIEW PAGE
  COURSE_OVERVIEW_BY: 'द्वारा',
  COURSE_OVERVIEW_LANGUAGE: 'भाषा',
  COURSE_OVERVIEW_PREVIEW_COURSE: 'पूर्वावलोकन पाठ्यक्रम',
  COURSE_OVERVIEW_TAKE_ASSESSMENT: 'आकलन करें',
  COURSE_OVERVIEW_ENTER_CLASSROOM: 'कक्षा में प्रवेश करें',
  COURSE_OVERVIEW_VIEW_ALL_COURSE: 'सभी कोर्स देखें',
  COURSE_OVERVIEW_COURSE_OUTLINE: 'पाठ्यक्रम की रूपरेखा',
  COURSE_OVERVIEW_OUTCOME: 'परिणाम',
  COURSE_OVERVIEW_LEVEL: 'स्तर',
  COURSE_OVERVIEW_PRE_REQUESTIES: 'पूर्व अनुरोध',
  COURSE_OVERVIEW_DURATION: 'अवधि',
  COURSE_OVERVIEW_WHO_SHOULD_ATTEND: 'किसे भाग लेना चाहिए',
  COURSE_OVERVIEW_JOB_ROLE: 'नौकरी की भूमिका',
  COURSE_OVERVIEW_INDUSTRY: 'उद्योग',
  COURSE_OVERVIEW_PRICE: 'मूल्य',
  COURSE_OVERVIEW_RESOURCES: 'पाठ्यक्रम संसाधन',
  // END COURSE OVERVIEW
  // CLASSROOM PAGE
  CLASSROOM_OBJECTIVE: 'अध्ययन के परिणाम',
  CLASSROOM_SEARCH_PLACEHOLDER: 'निम्न को खोजें...',
  CLASSROOM_COURSE_DETAILS: 'पाठ्यक्रम विवरण',
  // END CLASSROOM
  // Roles page(view Roles)
  VIEW_ROLES: 'रोल्स देखें',
  ROLES: 'भूमिकाएँ',
  SEARCH_ROLE: 'भूमिका खोजें',
  ROLE_NAME: 'भूमिका का नाम',
  ROLE_TYPE: 'भूमिका प्रकार',
  CREATED_ON: 'को निर्मित',
  START_DATE: 'आरंभ करने की तिथि *',
  END_DATE: 'अंतिम तिथि *',
  STATUS: 'स्थिति',
  VIEW_ROLE_NAME_INFO: '*संपादित करने के लिए भूमिका नाम पर क्लिक करें.',
  VIEW_ROLE_DATE_INFO: '*प्रारंभ और समाप्ति तिथियां अस्थायी भूमिकाओं के लिए हैं.',
  NO_ROLES_AVAILABLE: 'कोई रोल्स उपलब्ध नहीं हैं',
  // END View Roles
  // ASSESMENT LOCAlIZATION
  ASSESSMENT_START_TEST: 'परीक्षा शुरू करें',
  ASSESSMENT_NO_OF_QUESTION: 'प्रश्न संख्या',
  ASSESSMENT_NO_OF_ATTEMPTS: 'प्रयासों की संख्या',
  ASSESSMENT_TOTAL_MARKS: 'कुल अंक',
  ASSESSMENT_PASSING_MARKS: 'उत्तीर्ण अंक',
  ASSESSMENT_DURATION: 'अवधि',
  ASSESSMENT_PREV_QUESTION: 'पिछला प्रश्न',
  ASSESSMENT_NEXT_QUESTION: 'अगला प्रश्न',
  ASSESSMENT_SUBMIT_TEST: 'परीक्षा जमा करेें',
  ASSESSMENT_SL_NO: 'क्रमांक',
  ASSESSMENT_YOUR_SCORE: 'प्राप्तांक',
  ASSESSMENT_YOUR_MARKS: 'प्राप्तांक',
  ASSESSMENT_DATE: 'दिनांक',
  ASSESSMENT_TEST_STATUS: 'परिणाम',
  ASSESSMENT_RESULT: 'परिणाम',
  ASSESSMENT_PASS_MARKS: 'उत्तीर्ण अंक',
  ASSESSMENT_GO_TO_CHAPTER: 'अध्याय पर जाएं',
  ASSESSMENT_RETEST: 'पुन: परीक्षण',
  ASSESSMENT_GO_TO_CERTIFICATES: 'मेरे प्रमाणपत्रों पर जाएं',
  ASSESSMENT_CONFIRM_SUBMIT: 'क्या आप परीक्षण प्रस्तुत करना चाहते हैं?',
  ASSESSMENT_ANSWER_ALL: 'परीक्षण को प्रस्तुत करने से पहले सभी प्रश्न का उत्तर दें',
  ASSESSMENT_SUBMIT_TITLE: 'टेस्ट जमा करें',
  ASSESSMENT_SUBMIT_BUTTON: 'जमा करें',
  ASSESSMENT_PASS: 'आपने इस अध्याय को सफलतापूर्वक पूरा कर लिया है।',
  ASSESSMENT_CERTIFICATE_PASS: 'आपने इस पाठ्यक्रम को सफलतापूर्वक पूरा कर लिया है।',
  ASSESSMENT_FAIL: 'कृपया अध्याय का ध्यानपूर्वक अध्ययन करें।',
  ASSESSMENT_FINAL_FAIL: 'कृपया नीचे दिए गए अध्यायों का ध्यानपूर्वक अध्ययन करें।',
  ASSESSMENT_RECOMMENDATION: ' बेहतर अंक प्राप्त करने के लिए आप निम्नलिखित अध्यायों का अध्ययन कर सकते हैं।',
  ASSESSMENT_SELECT_ANSWER: 'एक उत्तर चुनें',
  ASSESSMENT_LABEL_PASS: 'उत्तीर्ण',
  ASSESSMENT_LABEL_FAIL: 'अनुत्तीर्ण',
  ASSESSMENT_GRADE: 'ग्रेड',
  // END ASSESSMENT
  // Forum page
  CATEGORIES: 'श्रेणियाँ',
  SEARCH_CATEGORIES_LABEL: 'श्रेणि खोजें',
  SEARCH_TOPICS_LABEL: 'विषय खोजें',
  TOPICS: 'विषय',
  CATEGORY_SELECT_LABEL: 'कृपया एक श्रेणि चयनित करें',
  POST: 'पोस्ट',
  TOPIC_SELECT_LABEL: 'कृपया एक विषय चयनित करें',
  NO_CATEGORIES_LABEL: 'कोई श्रेणियाँ नहीं',
  NO_TOPICS_LABEL: 'कोई विषय नहीं',
  SEARCH_POSTS: 'चयनित विषय के भीतर खोजें',
  SORT_BY_LABEL: 'क्रमबद्ध',
  RECENT_LABEL: 'हाल का',
  NO_POSTS_LABEL: 'कोई पोस्ट नहीं',
  START_DISCUSSION_LABEL: 'नई चर्चा शुरू करें',
  TRENDING_DISCUSSION_LABEL: 'ट्रेंडिंग चर्चाएँ',
  NO_DICUSSION_LABEL: 'कोई ट्रेंडिंग चर्चा नही',
  LOGIN_TO_VOTE: 'कृपया वोट करने के लिए लॉगिन करें.',
  LOGIN_TO_COMMENT: 'कृपया टिप्पणी करने के लिए लॉगिन करें.',
  LOGIN_TO_POST: 'कृपया नई चर्चा शुरू करने के लिए लॉगिन करें.',
  // Role Default
  ORGANIZATION_ROLE_OVERVIEW_LABEL: 'संगठन भूमिका अवलोकन',
  ORGANIZATION_NAME_LABEL: 'संगठन नाम',
  NO_OF_ROLES_LABEL: 'भूमिकाएँ की संख्या',
  // Login page
  FORGOT_PASSWORD: 'पासवर्ड भूल गए?',
  USERNAME_PLACEHOLDER: 'लॉग इन आईडी / ईमेल पता',
  INVALID_CREDENTIALS: 'अवैध प्रत्यय पत्र',
  // Course catalog page
  VIEW_ALL_COURSES_LINK: 'सभी पाठ्यक्रम देखें',
  VIEW_ALL_CATEGORIES_LINK: 'सभी श्रेणियाँ देखें',
  PARTICIPATE_IN_DISCUSSION_LINK: 'चर्चा में भाग लें',
  COURSE_CAROUSEL_WHAT_WOULD_YOU_LIKE_TO: 'आप क्या करना चाहते हैं',
  COURSE_CAROUSEL_TODAY: 'आज?',
  HOST_TYPE_VOCATIONAL_DESCRIPTION: `एक विशिष्ट रूप से तैनात प्रौद्योगिकी कंपनी जो इंजीनियरिंग और विनिर्माण ज्ञान को
  मिश्रित करती है वास्तविक जीवन के अनुभवों का अनुकरण करते हुए स्व-निर्देशित, डिजिटल रूप से इंटरैक्टिव उत्पादों का विकास करें।
  ज्ञान पोडियम खपत को आत्मसात करने, संस्थागत बनाने, वितरित करने और आश्वस्त करने के लिए व्यापक और सरल उत्पाद बनाता है
  किस संगठन के ज्ञान के मूल्य-श्रृंखला के पार। संगठन ने सफलतापूर्वक उत्पाद बनाए हैं इंजीनियरिंग, विनिर्माण, कौशल उन्नयन और
  ज्ञान प्रतिधारण प्रमुख उद्योगों और बड़े क   जरूरत है भारत और विदेशों में शिक्षण संस्थान.`,
  HOST_TYPE_TEACHERS_DESCRIPTION: `हम परिवर्तन में विश्वास करते हैं और इसलिए कहीं भ   पहुंचकर किस   को भ  अवसर प्रदान करते है
  दुनिया का सबस अच्छा सीखने का अनुभव। आप पाठ्यक्रमों की सूची से चुन सकते हैं, जो आपको विशेषज्ञता हासिल करने में मदद करता है
  ब्याज के क्षेत्र में। तो अपने समय और स्थान की चुनौतियों को गायब होने दें, और आप अपनी सीखने की यात्रा को आगे बढ़ाएं।
  आज आप जो सीखना चाहते हैं, उसे चुनें.`,
  COURSE_CAROUSEL_LEARN: ' सीखना ',
  // Footer
  CONTACT: 'संपर्क करें',
  QUICK_LINKS: 'त्वरित सम्पक',
  ABOUT_US: 'हमारे बारे में',
  TERMS_OF_USE: 'उपयोग की शर्तें',
  PRIVACY_POLICY: 'गोपनीयता नीति',
  CONTACT_US: 'हमसे संपर्क करें',
  FAQ: 'पूछे जाने वाले प्रश्न',
  HOW_TO: 'कैसे?',
  HAVE_A_QUESTION: 'सवाल है?',
  LEAVE_A_REPLY_MESSAGE: 'अपनी ईमेल आईडी नीचे छोड़ दें। हम आपसे संपर्क करेंगे।',
  EMAIL_PLACEHOLDER: 'ईमेल आईडी दर्ज करें',
  SELECT_LANGUAGE: 'भाषा चुनिए',
  //  Admin Licesne Page Labels
  ADMIN_LICENSE_LABEL_LICENSES: 'लाइसेंस',
  ADMIN_LICENSE_SEARCH_LICENSE_PLACE_HOLDER: 'खोज पाठ्यक्रम लाइसेंस',
  ADMIN_LICENSE_LICENSE_ID: 'लाइसेंस आईडी',
  ADMIN_LICENSE_COURSE_PRODUCT_NAME: 'कोर्स / उत्पाद का नाम',
  ADMIN_LICENSE_PURCHASE_DATE: 'खरीद की तारीख',
  ADMIN_LICENSE_QUANTITY: 'मात्रा',
  ADMIN_LICENSE_LICENSE_REMAINING: 'लाइसेंस शेष है',
  ADMIN_LICENSE_STATUS: 'स्थिति',
  ADMIN_LICENSE_LICENESE_VIEW_NOTE: '*लाइसेंस विवरण देखने के लिए पाठ्यक्रम नाम पर क्लिक करें',
  //  Admin License Details Page Labels
  ADMIN_LICENSE_DETAILS_LABEL_LICENSE_DETAILS: 'लाइसेंस विवरण',
  ADMIN_LICENSE_DETAILS_PRODUCT_NAME: 'उत्पाद का नाम',
  ADMIN_LICENSE_DETAILS_REQUEST_DATE: 'अनुरोधित तिथ',
  ADMIN_LICENSE_DETAILS_START_DATE: 'आरंभ करने की तिथिी',
  ADMIN_LICENSE_DETAILS_END_DATE: 'अंतिम तिथि',
  ADMIN_LICENSE_DETAILS_LICENSE_PURCHASED: 'लाइसेंस खरीदा गया',
  ADMIN_LICENSE_DETAILS_LICENSE_USED: 'लाइसेंस का इस्तेमाल किया',
  ADMIN_LICENSE_DETAILS_REQUEST_MORE_LICENSE_LABEL: 'अधिक लाइसेंस का अनुरोध करें',
  ADMIN_LICENSE_DETAILS_SEARCH_ADMIN: 'व्यवस्थापक खोजें',
  ADMIN_LICENSE_DETAILS_ADMIN_LICENSE_USER_NAME: 'सीखने वाला नाम',
  ADMIN_LICENSE_DETAILS_USER_EMAIL_ID: 'शिक्षार्थी ईमेल आईडी',
  ADMIN_LICENSE_DETAILS_ENROLLED_DATE: 'दाखिला तिथि',
  ADMIN_LICENSE_DETAILS_USER_PROGRESS: 'प्रगति',
  // Edit user and upload user data
  EMAIL: 'ईमेल',
  SITES: 'साइटें',
  COURSES: 'पाठ्यक्रम',
  SERCH_FOR_COURSE: 'पाठ्यक्रम की खोज करें..',
  UPLOAD_USER_DATA: 'पउपयोगकर्ता डेटा अपलोड करें',
  CENTER: 'केंद्र',
  SELECT_CENTER: 'केंद्र का चयन करें',
  ASYNC_FIELD: 'Async फ़ील्डं',
  FILE_NAME: 'फ़ाइल का नाम',
  FILE_SELECTION: 'फ़ाइल चयन',
  DOWNLOAD_EXCEL_TEMPLATE: 'एक्सेल टेम्पलेट डाउनलोड करें',
  UPLOAD_DIRTY_MSG: ' आवश्यक है.',
  UPLOAD_FILE: 'दस्तावेज अपलोड करें',
  SEAT_AVAILABLE: 'सीट उपलब्ध है',
  STUDENT_SELECTED: 'छात्र का चयन',
  STUDENT: 'छात्र',
  CREATE_USER: 'उपयोगकर्ता बनाइये',
  EDIT_USER_ACCOUNT: 'उपयोगकर्ता खाता संपादित करें',
  SELECT_FILE: 'फ़ाइल का चयन करें',
  LEARNER_DETAILS: 'शिक्षार्थी विवरण',
  LICENSE_NUMBER: 'लाइसेंस संख्या',
  ENRROLLED_END_DATE: 'लाइसेंस की अंतिम तिथि',
  LICENSE_STATUS: 'लाइसेंस की स्थिति',
  ENROLLED_DATE: 'दाखिला तिथि',
  SEARCH_COURSES: 'कोर्स खोजें',
  CREATE_USER_ACCOUNT: 'व्यक्तिगत उपयोगकर्ता खाता बनाएँ',
  ENROLLED_TO_OTHER_ORG_SUBTITLE_MSG: 'नोट: कृपया नीचे सूचीबद्ध अन्य ईमेल आईडी के साथ नामांकन करें',
  UNABLE_TO_UPLOAD_BULK_USER_FILE: 'फाइल अपलोड करने में असमर्थ.कृपया मान्य फ़ाइल प्रारूप का चयन करें',
  USER_ENROLLED_TO_COURSE_SUBTITLE_MSG: 'नोट: कृपया नामांकन के साथ आगे बढ़ने के लिए सूचीबद्ध उपयोगकर्ता को हटा दें',
  INSUFFICIENT_LICENSE_SUBTITLE_MSG:
    'नोट: कृपया उपलब्ध सीटों की वैध संख्या के साथ कोर्स का चयन करें या कुछ छात्रों को हटा दें',
  DELETE_USER: 'उपभोक्ता मिटायें',
  UPLOAD_LEARNERS: 'शिक्षार्थियों को अपलोड करें',

  // Dashboard
  DASHBOARD_RECENTLY_VIEWED: 'हाल ही में देखा गया',
  DASHBOARD_MY_COURSES: 'मेरे पाठ्यक्रम',
  DASHBOARD_RECOMMENDED_COURSES: 'अनुशंसित पाठ्यक्रम',
  DASHBOARD_COURSES_PROGRESS: 'प्रगति',
  DASHBOARD_CREATED_BY: 'के द्वारा बनाई गई',
  DASHBOARD_POD: 'POD:',
  VIEW_ALL: 'सभी देखें',
  TAKE_ASSESSMENT: 'आकलन ले',
  ENTER_CLASSROOM: 'कक्षा दर्ज करें',
  PREVIEW_COURSE: 'पूर्वावलोकन',
  NO_SUBSCRIPTION: 'प्रदर्शित करने के लिए कोई वर्तमान सदस्यता नहीं है',
  CURRENT_SUBSCRIPTION: 'वर्तमान सदस्यताएं',
  COURSE_NAME: 'पाठ्यक्रम का नाम',
  COURSE_PROGRESS: 'पाठ्यक्रम प्रगति',
  SUBSCRIPTION_LEFT: 'सदस्यता का दिन बचा हुआ',
  NO_PAST_SUBSCRIPTION: 'प्रदर्शित करने के लिए कोई पूर्व सदस्यता नहीं है',
  PAST_SUBSCRIPTION: 'पिछले सदस्यताएं',
  EXPIRED_DATE: 'समयसीमा समाप्त दिनांक',
  NOT_PERMITTED: 'अनुमति नहीं है.',
  COURSE_LEVEL: 'कोर्स स्तर ',

  // discussion
  DISCUSSION_FORUMS_FIELD: 'फ़ोरम *',
  DISCUSSION_FORUM_LABEL: 'फ़ोरम टाइप करें',
  DISCUSSION_TOPIC_FIELD: 'विषय *',
  DISCUSSION_TOPIC_LABEL: 'विषय टाइप करें',
  DISCUSSION_LEVEL_FIELD: 'सबसे अच्छा अपने विषय के "स्तर" *',
  DISCUSSION_TITLE_FIELD: 'शीर्षक *',
  DISCUSSION_TITLE_LABEL: 'शीर्षक टाइप करे',
  DISCUSSION_DESCRIPTION_FIELD: 'विवरण *',
  DISCUSSION_REQUIRED: 'विवरण आवश्यक है.',
  POST_DISCUSSION: 'चर्चा भेजें',
  PREVIEW_DISCUSSION: 'पूर्वावलोकन',
  EDIT_DISCUSSION: 'संपादित',
  DISCUSSION_POST: 'चर्चा भेजें',
  REPLY_COMMENT: 'जवाब दे',
  COMMENT_FLAG: 'फ्लैग',
  DISCUSSION_COMMENTS: 'टिप्पणियाँ',
  ADD_COMMENT: 'टिप्पणी जोड़ें',

  // OrgAdminRequests
  REQUEST_TYPE: 'अनुरोध का प्रकार*',
  REQUEST_DETAILS: 'अनुरोध विवरण*',
  SELECT_REQUEST_TYPE: 'अनुरोध प्रकार चुनें',
  SEARCH_COURSE: 'कोर्स की खोज करें',
  REQUEST_DETAILS_PLACEHOLDER:
    'आपके अनुरोध का संक्षेप में वर्णन करें और हमारे एक ग्राहक प्रतिनिधि 24 घंटे के भीतर जवाब देंगे।',
  ORG_ADMIN_REQUESTS_SUBMIT: 'जमा करें',
  ORG_ADMIN_REQUESTS_HEADING: 'कृपया हमें बताएं कि हम आपकी कैसे मदद कर सकते हैं',
  ORG_ADMIN_REQUESTS_SUBHEADING: '*तकनीकी समस्याओं की तत्काल मदद के लिए कृपया हमारे विक्रय प्रतिनिधि को कॉल करें।',
  // My Certificate
  MYCERTIFICATE_HEADING: 'मेरा प्रमाण पत्र',
  NO_CERTIFICATE: 'कोई प्रमाण पत्र नहीं मिला .',
  VIEW_CERTIFICATE: 'प्रमाणपत्र देखें',
  // Modal
  MODAL_OK: 'ठीक है',
  MODAL_CANCEL: 'रद्द करें',
  // End Modal

  // <-- url: /admin/detail,  Admin Detail page localization start -->

  ADMIN_ACCOUNT_DETAILS: 'व्यवस्थापक खाता विवरण',
  ORGASNISATION_NAME: 'संगठन का नाम',
  ADMIN_FIRST_NAME: 'व्यवस्थापक का पहला नाम',
  ADMIN_LAST_NAME: 'व्यवस्थापक का अंतिम नाम',
  ADMIN_EAIL_ID: 'व्यवस्थापक की ईमेल आईडी',
  ADMIN_MOBILE_NO: 'व्यवस्थापक का मोबाइल नं',
  ADMIN_CONTACT_US_PLEASE: 'खाते के विवरण को संशोधित करने या अपडेट करने के लिए कृपया हमसे',
  ADMIN_CONTACT_US_UPDATE: '',
  ADMIN_CONTACT_US: 'संपर्क करें',

  // Admin home screen welcme message
  ADMIN_ROUTEPAGE_WELCOME: 'आपका स्वागत है',
  ADMIN_ROUTEPAGE_ADMINISTRATOR: 'प्रशासक',
  SEE_COURSE_DETAILS: 'पाठ्यक्रम विवरण देखें',
  MY_COURSES: 'मेरे पाठ्यक्रम',
  SORT_BY: 'इसके अनुसार क्रमबद्ध करें',

  NO_RECORDS_FOUND: 'कोई रिकॉर्ड नहीं मिला',
  // EDUCATION_QUALIFICATIONS
  EDUCATION_QUALIFICATIONS: 'शैक्षणिक योग्यता',
  LEVEL_OF_EDUCATION: 'शिक्षा का स्तर',
  INSTITUTION_NAME: 'संस्था का नाम',
  FIELD_OF_STUDY: 'अध्ययन की शाखा',
  PERCENTAGE: 'प्रतिशत',
  YEAR_OF_GRADUATION: 'स्नातक स्तर की पढ़ाई का साल',
  CURRENTLY_PURSUING: 'वर्तमान में जारी है',
  SELECT_EDUCATION: 'शिक्षा का चयन करें',
  SAVE_EDUCATION: 'Save शिक्षा',
  ADD_EDUCATION: 'शिक्षा जोड़ें',
  NAME_OF_THE_INSTITUTION: 'संस्था का नाम',
  EDUCATION_DELETE_ALERT_LABEL: 'क्या आप वाकई इस शिक्षा को हटाना चाहते हैं?',
  DELETE_EDUCATION_CONFIRMATION: 'शिक्षा पुष्टिकरण हटाएं',

  // Create Site
  CREATE_ORGANISATION_CENTER: 'संगठन केंद्र बनाएं',
  EDIT_ORGANISATION_CENTER: 'संगठन केंद्र संपादित करें',
  CENTER_NAME: 'केंद्र का नाम',
  CITY: 'शहर',
  CENTER_ADMINS: 'केंद्र व्यवस्थापक',
  SELECT_ADMIN: 'व्यवस्थापक चुनें',
  CREATE_CENTER: 'केंद्र बनाएं',
  RECOMMENDED_COURSES: 'अनुशंसित पाठ्यक्रम',
  WORK_EXPERIENCE: 'काम का अनुभव',
  DELETE_WORK_EXPERIENCE_CONFIRMATION: 'कार्य अनुभव पुष्टि हटाएँ',
  WORK_EXPERIENCE_DELETE_ALERT_LABEL: 'क्या आप वाकई इस कार्य अनुभव को हटाना चाहते हैं?',
  JOB_TITLE: 'नौकरी का नाम *',
  ORG: 'संगठन *',
  START_MONTH: 'महीने की शुरुआत',
  START_YEAR: 'साल की शुरुआत',
  END_MONTH: 'महीने की  समाप्त',
  END_YEAR: 'साल की समाप्त',
  CURRENTLY_WORKING: 'वर्तमान में काम कर रहे हैं?',
  JOB_DESC: 'नौकरी का विवरण',
  TO: 'to',
  ENTER_JOB_TITLE: 'नौकरी का शीर्षक दर्ज करें',
  ENTER_ORG_NAME: 'संगठन का नाम दर्ज करें',
  MONTH: 'महीना',
  YEAR: 'साल',
  JOB_RESP_ACHIVEMENTS: 'नौकरी की जिम्मेदारियों और उपलब्धियों की सूची बनाएं',
  ADD_JOB: 'नौकरी जोड़ें',
  UPDATE_JOB: 'नौकरी अपडेट करें',
  MY_SKILLS: 'मेरे कौशल',
  SKILLS: 'कौशल',
  SKILL: 'कौशल',
  YEARS: 'वर्षों',
  EXPERIENCE: 'अनुभव',
  MONTHS: 'महीने',
  UPDATE_SKILL: 'अद्यतन कौशल',
  ADD_SKILL: 'कौशल जोड़ें',
  TYPE_SKILL_NAME: 'कौशल नाम लिखें',
  // const for /user/certificates page starts
  CERTIFICATE_HEADING: 'प्रमाण पत्र',
  CERTIFICATE_NAME_LABEL: 'प्रमाण - पत्र नाम *',
  CERTIFICATE_NAME_PLACEHOLDER: 'प्रमाण - पत्र नाम',
  CERTIFICATE_AWARDED_BY_LABEL: 'सम्मानित किया गया/संगठन *',
  CERTIFICATE_AWARDED_BY_PLACEHOLDER: 'संगठन नाम',
  CERTIFICATE_DATE_RECEIVED_LABEL: 'प्राप्ति दिनांक *',
  CERTIFICATE_DATE_RECEIVED_PLACEHOLDER: 'DD/MM/YYYY',
  CERTIFICATE_UPLOAD_CERTIFICATE_BUTTON: 'प्रमाणपत्र अपलोड करें *',
  CERTIFICATE_ADD_OR_EDIT_BUTTON: 'प्रमाणपत्र जोड़ें / संपादित करें',
  CERTIFICATE_ADDING_CERTIFICATE_BUTTON: 'प्रमाण पत्र जोड़ना',
  CERTIFICATE_UPLOADING_CERTIFICATE_BUTTON: 'प्रमाण पत्र अपलोड करना',
  CERTIFICATE_CANCEL_BUTTON: 'रद्द करें',
  CERTIFICATE_TABLE_CERTIFICATE_NAME_HEADING: 'प्रमाण - पत्र नाम',
  CERTIFICATE_TABLE_AVARDED_BY_HEADING: 'सम्मानित किया गया/संगठन नाम',
  CERTIFICATE_TABLE_RECEIVED_DATE_HEADING: 'प्राप्त तारीख',
  CERTIFICATE_VIEW_BUTTON: 'प्रमाणपत्र देखें',
  CERTIFICATE_TABLE_INFO: '* संपादित करने के लिए प्रमाणपत्र नाम पर क्लिक करें',
  // const for /user/certificates page ends
  // const for /passwordchange page starts
  CHANGE_PASSWORD_HEADING: 'पासवर्ड बदलें',
  CHANGE_PASSWORD_OLD_PASSWORD_LABEL: 'पुराना पासवर्ड *',
  CHANGE_PASSWORD_OLD_PASSWORD_PLACEHOLDER: 'पुराना पासवर्ड',
  CHANGE_PASSWORD_NEW_PASSWORD_LABEL: 'नया पासवर्ड *',
  CHANGE_PASSWORD_NEW_PASSWORD_PLACEHOLDER: 'नया पासवर्ड',
  CHANGE_PASSWORD_CONFIRM_PASSWORD_LABEL: 'पासवर्ड की पुष्टि कीजिये *',
  CHANGE_PASSWORD_CONFIRM_PASSWORD_PLACEHOLDER: 'पासवर्ड की पुष्टि कीजिये',
  CHANGE_PASSWORD_SUBMIT_BUTTON: 'जमा करें',
  // const for /passwordchange page ends
  // Recommended Courses
  RECOMMENDED_CHAPTER_NAME: 'अध्याय',
  RECOMMENDED_WRONG_ANSWER_COUNT: 'गलत जवाब नहीं',

  // Added the missing keys from ENGLISH
  IS_REQUIRED: ' आवश्यक है.',
  BASIC_INFORMATION: 'बुनियादी जानकारी',
  MY_INFO: 'मेरी जानकारी',
  MOBILE_NO: 'मोबाइल नंबर',
  GENDER: 'लिंग',
  DOB: 'जन्म की तारीख',
  ADDRESS: 'पता',
  MARITAL_STATUS: 'वैवाहिक स्थिति',
  ADDRESS_LINE_1: 'पता पंक्ति 1',
  ADDRESS_LINE_2: 'पता पंक्ति नं 2',
  ENTER_ADDRESS_LINE_1: 'पता पंक्ति 1 दर्ज करें',
  ENTER_ADDRESS_LINE_2: 'पता पंक्ति 2 दर्ज करें',
  ENTER_CITY: ' शहर दर्ज करें ',
  STATE: 'राज्य',
  ENTER_STATE: ' राज्य दर्ज करें ',
  COUNTRY: 'देश',
  ENTER_COUNTRY: 'देश दर्ज करें ',
  PINCODE: 'पिन कोड',
  ENTER_PINCODE: 'पिन कोड दर्ज करें ',
  ROLE_START_DATE_LABEL: 'भूमिका प्रारंभ दिनांक (अगर अस्थायी)',
  ROLE_END_DATE_LABEL: 'भूमिका समाप्ति तिथि (अगर अस्थायी)',
  NEXT: 'आगामी',
  DELETE: 'हटाएं',
  DELETE_ROLE: 'भूमिका हटाएँ',
  ROLE_NAME_PLACEHOLDER: 'भूमिका नाम दर्ज करें',
  ROLE_TYPE_PLACEHOLDER: 'भूमिका प्रकार चुनें',
  CREATE_ROLE_LABEL: 'भूमिका बनाएँ',
  EDIT_RESPONSIBILITIES_LABEL: 'जिम्मेदारी संपादित करें',
  ROLE_DELETE_ALERT_LABEL: 'क्या आप वाकई इस भूमिका को हटाना चाहते हैं?',
  ROLE_IN_USER_LABEL: 'भूमिका उपयोग में है .कृपया निम्नलिखित प्रवेशों के लिए भूमिकाएँ बदलें और पुनः प्रयास करें .',
  EDIT_ROLE: 'भूमिका संपादित करें',
  REGULAR_LABEL: 'नियमित',
  TEMPORARY_LABEL: 'अस्थायी',
  // verify email
  PROCEED_BUTTON: 'बढ़ना',
  RESEND_BUTTON: 'पुन: भेजें',
  VERIFY_EMAIL_LINK_SUCCESS_MSG:
    'बधाई हो, आपका ईमेल सफलतापूर्वक सत्यापित हो गया है कृपया लॉगिन करने के लिए नीचे क्लिक करें',
  VERIFY_EMAIL_LINK_FAILURE_MSG: 'क्षमा करें, आपका लिंक समाप्त हो गया है। लिंक को पुनः भेजें कृपया नीचे क्लिक करें',
  // end of verify email
  // view Users
  NUMBER_OF_ENROLLED_PODS: 'निर्धारित पाठ्यक्रमों की संख्या',
  NUMBER_OF_COMPLETED_PODS: 'पूर्ण पाठ्यक्रमों की संख्या',
  CLICK_ON_USER_NAME_TO_EDIT: 'संपादित करने के लिए उपयोगकर्ता नाम पर क्लिक कर',
  SEARCH_USERS: 'खोज का उपयोग करे',
  LEARNER_NAME: 'सीखने वाला नाम',

  // Delete Certificate confirmation
  DELETE_CERTIFICATE_CONFIRMATION: 'क्या आप निश्चयपूर्वक यह प्रमाणपत्र हटाना चाहते हैं?',
  DELETE_CONFIRMATION_TITLE: 'प्रमाणपत्र पुष्टिकरण हटाएं',

  APPROVE_LEARNER_CONFIRMATION: 'क्या आप वाकई इस शिक्षार्थी का अनुमोदन करना चाहते हैं?',
  APPROVE_LEARNER_CONFIRMATION_TITLE: 'शिक्षार्थी की पुष्टि करें',
  REJECT_LEARNER_CONFIRMATION: 'क्या आप वाकई इस शिक्षार्थी को अस्वीकार करना चाहते हैं?',
  REJECT_LEARNER_CONFIRMATION_TITLE: 'शिक्षार्थी की पुष्टि को अस्वीकार करें',

  SHOW_ADD_COMMENT_ERROR: 'टिप्पणी आवश्यक है.',

  LOOKING_FOR: 'तुम क्या ढूंढ रहे हो ?',
  REFINE_SEARCH: 'खोज को परिष्कृत करें',
  RESET: 'रीसेट',
  INDUSTRY: 'उद्योग',
  TYPE: 'प्रकार',
  SKILL_LEVEL: 'कौशल स्तर',
  SELECT: 'नते हैं',
  END_RESULT: 'परिणामों का अंत',
  VIEW: 'राय',
  COURSES_CATALOG: 'पाठ्यक्रम',
  COURSE_DURATION: 'कोर्स की अवधि:',
  LEARN_MORE: 'और अधिक जानें',
  // Missing Keys:
  DATE: 'दिनांक',
  ALL: 'सब',
  A_Z: 'A-Z',
  Z_A: 'Z-A',
  READ: 'पढ़ें',
  UNREAD: 'अपठित ग',
  FILTER_BY_LABEL: 'के द्वारा छनित',
  NO_RESULTS_TO_SHOW: 'और कोई परिणाम नहीं दिखा .',
  NO_CONVERSATIONS: 'प्रदर्शित करने के लिए कोई वार्तालाप नहीं .',
  NO_ACTIVE_CONVERSATION: 'कोई सक्रिय बातचीत प्रदर्शित करने के लिए .',
  CREATE_CONVERSATION: 'नई बातचीत शुरू करें',
  DELETE_CONVERSATION: 'चयनित वार्तालाप हटाएं',
  ADD_CONNECTION: 'कनेक्शन जोड़ें',
  BLOCK_CONNECTION: 'ब्लॉक कनेक्शन',
  UNBLOCK_CONNECTION: 'कनेक्शन को अनब्लॉक करें',
  CONVERSATION_DELETE_ALERT_LABEL: 'क्या आप वाकई चयनित वार्तालाप को हटाना चाहते हैं?',
  DELETE_CONVERSATION_LABEL: 'चयनित वार्तालाप पुष्टि हटाएं',
  SEARCH_CONNECTION_LABEL: 'कनेक्शन खोजें',
  CONNECT_LABEL: 'जुडिये',
  NO_PREVIOUS_CONVERSATION: 'प्रदर्शित करने के लिए कोई पिछली बातचीत नहीं',
  TYPE_NAME: 'एक नाम टाइप करें',
  ADD_CONNECTION_PLACEHOLDER: 'उस उपयोगकर्ता का ईमेल आईडी दर्ज करें जिसे आप जोड़ना चाहते हैं',
  ACCEPT_LABEL: 'स्वीकार करना',
  REJECT_LABEL: 'अस्वीकार',
  ACTIONS: 'क्रिया',
  SEND_ADD_REQUEST_LABEL: 'अनुरोध भेजें',
  DENY_LABEL: 'मना',

  DELETE_SKILL_CONFIRMATION: 'क्या आप वाकई इस कौशल को हटाना चाहते हैं?',
  DELETE_TITLE_SKILL_CONFIRMATION: 'कौशल पुष्टिकरण हटाएं',
  // enter classroom and preview classroom button
  ENTER_CLASSROOM_EXPIRES:
    'कोर्स लाइसेंस समाप्त हो गया है। कक्षा में प्रवेश करने के लिए, कृपया लाइसेंस को नवीनीकृत करें / लाइसेंस को नवीनीकृत करने के लिए अपने व्यवस्थापक से संपर्क करें',
  ENTER_CLASSROOM_RECOMMENDED: 'आप पाठ्यक्रम को खरीदे बिना केवल 2 लिंक देख सकते हैं',
  SCHOOL: 'शाला',
  DISTRICT: 'जिला',
  // Reports
  REPORT_PAGE_TITLE: 'विवरण',
  REPORT_SEARCH_LABEL: 'राज्य, जिला, ब्लॉक, स्कूल या छात्र के लिए उपलब्ध रिपोर्टें खोजें',
  REPORT_SEARCH_PLACEHOLDER: 'जिला, ब्लॉक, स्कूल या छात्र के नाम से खोजेंं',
  REPORT_ALL_DISTRICTS: 'सभी जिले',
  REPORT_ALL_BLOCKS: 'सभी ब्लॉक',
  REPORT_ALL_SCHOOLS: 'सभी स्कूल',
  REPORT_SUMMARY_TITLE: 'शिक्षक प्रशिक्षण कार्यक्रम सारांश',
  REPORT_DOWNLOAD_LABEL: 'सारांश डाउनलोड करें',
  REPORT_TOTAL_LEARNERS_LABEL: 'कुल छात्र',
  REPORT_ACTIVE_COURSES_LABEL: 'सक्रिय पाठ्यक्रम',
  REPORT_ACTIVE_ENROLLMENTS_LABEL: 'सक्रिय नामांकन',
  REPORT_COURSES_INPROGRESS_LABEL: 'प्रगति में कुल पाठ्यक्रम',
  REPORT_CERTIFICATE_AWARDED_LABEL: 'प्रमाणपत्र से सम्मानित किया गया',
  REPORT_STATISTICS_AND_ANALYTICS_LABEL: 'सांख्यिकी और विश्लेषण',
  REPORT_TOTAL_COURSES_LABEL: 'कुल पाठ्यक्रम',
  REPORT_TOTAL_STUDENT_LABEL: 'कुल छात्र',
  REPORT_INPROGRESS_LABEL: 'प्रगति में है',
  REPORT_YET_TO_START_LABEL: 'लंबित शुरुआत',
  REPORT_COMPLETED_LABEL: 'पूरा कर लिया है',
  REPORT_ENROLLED_LABEL: 'सक्रिय',
  REPORT_INACTIVE_LABEL: 'निष्क्रिय',
  REPORT_CERTIFICATE_AWARDED_TITLE: 'सम्मानित प्रमाणपत्र बनाम पाठ्यक्रम',
  REPORT_STUDENT_VS_COURSES_TITLE: 'छात्र बनाम उपलब्ध पाठ्यक्रम',
  REPORT_DISTRICTS_DIRECTORY_LABEL: 'जिले की निर्देशिका',
  REPORT_STATE_LABEL: 'राज्य:',
  REPORT_KARNATAKA: 'कर्नाटक',
  REPORT_VIEW_REPORTS_LABEL: 'रिपोर्ट देखें',
  REPORT_DISTRICT_NAME_HEADING: 'जिला का नाम',
  REPORT_BLOCKS_HEADING: 'ब्लाकों',
  REPORT_HEADING: 'रिपोर्ट',
  REPORT_FIND: 'खोजों',
  REPORT_VIEW_ALL: 'सभी को देखें',
  REPORT_BLOCK_NAME_HEADING: 'ब्लॉक का नाम',
  REPORT_SCHOOLS_HEADING: 'स्कूलों',
  REPORT_SCHOOL_NAME_HEADING: 'विद्यालय का नाम',
  REPORT_DISTRICT_LEVEL: 'जिला',
  REPORT_BLOCK_LEVEL: 'ब्लॉक',
  REPORT_SCHOOL_LEVEL: 'विद्यालय',
  // End Reports
  COURSE_RESOURCE: 'संसाधन',
  MAX_LENGTH_EXCEEDED: 'अधिकतम लंबाई पार हो गई !!',
  // Contact
  KP_CONTACTDETAILS_LINE_1: '21, सिडकुल आईटी पार्क, सहस्त्रधारा',
  KP_CONTACTDETAILS_LINE_2: 'रोड, देहरादून - 248001,',
  KP_CONTACTDETAILS_STATE: 'उत्तराखंड,',
  KP_CONTACTDETAILS_COUNTRY: 'भारत',
  KP_CONTACTDETAILS_PHONE_NUMBER: 'पी: +91 97564 31011',
  KP_CONTACTDETAILS_EMAILID: 'ई: contact@knowledgepodium.com',
  EDIT_PERMISSION_DENIED: 'आपके पास संपादन करने की अनुमति नहीं है',

  CANCEL_ADD_REQUEST: 'जोड़ें अनुरोध रद्द करें',

  // USER BASIC INFO
  SCHOOLDETAILS: 'स्कूल की जानकारी',
  // SCHOOL: 'स्कूल',
  BLOCK: 'ब्लॉक',

  // SELF_REGISTRATION
  SELF_REGISTRATION: 'व्यक्तिगत पंजीकरण',
  CONTINUE: 'मोबाइल नंबर सत्यापित करें।ें',
  TEACHERS_TRAINING_SIGN_UP: 'शिक्षक प्रशिक्षण पंजीकरण',
  BASIC_INFO_SCHOOL_INFO: 'बुनियादी जानकारी और स्कूल जानकारी',
  SIGN_UP: 'साइन अप करें',
  ACTIVE_USERS: 'सक्रिय उपयोगकर्ता',
  DELETED_USERS: 'हटाए गए उपयोगकर्ता',
  PENDING_LIST: 'लंबित सूची',
  SUCCESSFULL_REGISTRATION: 'आप सफलतापूर्वक रजिस्ट्र हो गए है!',
  FOLLOW_INSTRUCTIONS: 'ईमेल में दिए गए निर्देशों का पालन करें.',
  // CONTINUE: 'जारी रखें',
  OTP_VERIFY: 'OTP सत्यापित करें',
  BASIC_INFO: 'मूलभूत जानकारी',
  FEEDBACK: 'प्रतिक्रिया',
  BEGIN_SURVEY: 'सर्वेक्षण शुरू करें',
  WE_VALUE_YOUR_FEEDBACK: 'हम आपकी प्रतिक्रिया को महत्व देते हैं',
  DESCRIPTION_FOR_FEEDBACK:
    'कर्नाटक राज्य सरकार इस नए शिक्षक प्रशिक्षण कार्यक्रम पर आपकी प्रतिक्रिया चाहेगी। यह सर्वेक्षण करके हमारे मंच और अन्य पाठ्यक्रमों को बेहतर बनाने में हमारी मदद करें।',
  // grace Period
  GRACE_PERIOD_MESSAGE: 'आपका लाइसेंस समाप्त हो जाएगा',
  DAYS: 'दिनों में. जारी रखने के लिए लाइसेंस को नवीनीकृत करें.',

  // Course Progress Report
  FAILED_TO_FETCH_COURSE_PROCESS: 'पाठ्यक्रम प्रगति विवरण लाने में विफल',
  PROGRESS_COMPLETED_LABEL: 'पूरा किया',
  PROGRESS_INCOMPLETE_LABEL: 'अपूर्ण',
  PROGRESS_CHAPTERS_LABEL: 'अध्याय',
  ASSESSMENT_ATTEMPTED: 'प्रयास दिनांक',
  ASSESSMENT_SCORE: 'स्कोर',
  UNWATCHED_VIDEOS: 'बिना देखे वीडियो',
  COURSE_PROGRESS_REPORT: 'प्रगति',

  DELETE_ROLE_TITLE: 'रोल पुष्टिकरण हटाएं',
  ANSWER: 'उत्तर',

  YOUR_FEEDBACK_IS_IMPORTANT_TO_US: 'आपकी प्रतिक्रिया हमारे लिए महत्वपूर्ण है',

  USER_DELETE_ALERT_LABEL: 'क्या आप वाकई इस उपयोगकर्ता को हटाना चाहते हैं?',

  // My Journal DashBoard
  RJ_MY_JOURNAL: 'मेरी पत्रिका',
  RJ_MY_COURSES: 'मेरे पाठ्यक्रम',
  NO_POD_AVAILABLE: 'आपने किसी कोर्स के लिए सदस्यता नहीं ली है। कृपया अपने साइट व्यवस्थापक से संपर्क करेें',
  DOWNLOAD_CHAPTER: 'अध्याय डाउनलोड करें',
  DOWNLOAD_ALL: 'सभी डाउनलोड',
  DOWNLOAD_MODULE: 'मॉड्यूल डाउनलोड करें',
  JOURNAL_COMPLETED: 'पूरा कर लिया है',
  JOURNAL_RESUME: 'बायोडाटा',
  DOWNLOAD_COURSE: 'पाठ्यक्रम डाउनलोड करें',
  DOWNLOAD_JOURNALS: 'पत्रिका डाउनलोड करें',
  RJ_SEARCH_JOURNAL: 'पत्रिका खोजें',
  // End My Journal Dashboard

  HOME: 'होम',
  LEVEL_OF_EDUCATION_PURSUNING: 'आप किस स्तर की शिक्षा प्राप्त कर रहे हैं?',
  FIRST_STEP: 'Take your first step to getting an',
  EDUCATION_IN_INDIA: 'education in India',
  REGISTRATION: 'पंजीकरण',

  POSTS: 'चर्चाएँ',
  FORUMS: 'पदों',
  SEARCH_FORUMS: 'फ़ोरम खोजें',
  SEARCH_POSTS_NEW: 'पदों खोजें',
  LAST_POST: 'अंतिम पोस्ट',
  RESUME_NOW: 'रेशीम नौं',
  RESULTS_FOUND: 'परिणाम मिले',

  // contact us new
  PURPOSE_OF_INQUIRY: 'जांच का उद्देश्य',
  NAME: 'नाम',
  MOBILE: 'मोबाइल',
  YOUR_MESSAGE: 'आपका सन्देश',
  SUBMIT: 'जमा करें',
  // end of contact us new

  EDIT_ADD_SEND_REQUEST_LABEL: 'संदेश संपादित करें और भेजें',
  SAVE: 'बचाना',
  REGISTER: 'रजिस्टर',
};
