export default {
  // This is ENGLISH language specific constant file
  // Organization Structure Page
  LOGIN: 'साइन इन',
  USER_NAME: 'वापरकर्तानाव',
  PASSWORD: 'पासवर्ड',
  ORG_STRUCTURE_SUB_HEADING: ' संघटना संरचना',
  NO_OF_SUB_ORGS_LABEL: 'विभागांची संख्या',
  NO_OF_ADMINS_LABEL: 'प्रशासनाची संख्या',
  NO_OF_USERS_LABEL: 'शिकणार्यांची संख्या',

  // *t common labels
  REQUIRED_FIELD: '*',
  FIRST_NAME: 'पहिले नाव',
  MIDDLE_NAME: 'मधले नाव',
  LAST_NAME: 'आडनाव',
  MOBILE_NUMBER: 'मोबाइल नंबर',
  PARENTS_MOBILE_NUMBER: 'पालकांचे मोबाइल नंबर',
  MOBILE_NO_REGISTERED: 'मोबाइल नंबर आधीपासूनच नोंदणीकृत आहे.',
  EMAIL_ID: 'ई - मेल आयडी',
  EMAIL_REGISTERED: 'ईमेल आयडी आधीच नोंदणीकृत आहे.',
  SAVE_CHANGES: 'बदल जतन करा',
  CANCEL: 'रद्द करा',
  IS_REQUIRED: ' आवश्यक आहे.',
  DATE: 'तारीख',
  ALL: 'सर्व',
  A_Z: 'अ - झ',
  Z_A: 'झ - अ',
  READ: 'वाचलेले',
  UNREAD: 'न वाचलेले',
  FILTER_BY_LABEL: 'द्वारे फिल्टर',
  // ENd common labels

  // *t viewadmins page labels
  VIEW_ORGANIZATION_ADMINS: 'संस्था प्रशासक पहा',
  SEARCH_ADMIN_BY_NAME: 'नावाने प्रशासक शोधा',
  NO_ADMIN_ACCOUNT_FOUND: 'प्रशासक खाते आढळले नाही',
  ADMINS: 'प्रशासक',
  ADMIN_NAME: 'प्रशासक नाव',
  CENTER_OR_SITE: 'ब्लॉक',
  ROLE: 'भूमिका',
  CLICK_ADMINNAME_TO_EDIT: '* संपादनासाठी प्रशासकीय नावावर क्लिक करा',
  CREATE_ADMIN_ACCOUNT: 'प्रशासक खाते तयार करा',
  // End viewadmins page labels

  // *t createadmin page labels
  CREATE_ADMIN: 'प्रशासक तयार करा',
  EDIT_ADMIN: 'प्रशासक संपादित करा',
  SELECT_ROLES: 'भूमिका निवडा',
  // End createadmin page labels

  VIEW_ORGANIZATION_CENTERS: 'संस्था ब्लॉक्स पहा',
  SEARCH_CENTERS: 'ब्लॉक्स शोधा',
  NO_CENTERS_FOUND: 'कोणतेही ब्लॉक्स सापडले नाहीत',
  CENTERS: 'ब्लॉक्स',
  CENTERS_OR_SITES: 'ब्लॉक्स',
  DATE_CREATED: 'तयार केल्याची तारीख',
  CLICK_ON_SITES_TO_EDIT: 'संपादित करण्यासाठी ब्लॉकवर क्लिक करा',
  CREATE_CENTERS_SITES: 'ब्लॉक तयार करा',
  // const for /user/certificates page *ts
  CERTIFICATE_HEADING: 'प्रमाणपत्र',
  CERTIFICATE_NAME_LABEL: 'प्रमाणपत्र नाव',
  CERTIFICATE_NAME_PLACEHOLDER: 'प्रमाणपत्र नाव',
  CERTIFICATE_AWARDED_BY_LABEL: 'द्वारा पुरस्कृत',
  CERTIFICATE_AWARDED_BY_PLACEHOLDER: 'संस्थेचे नाव',
  CERTIFICATE_DATE_RECEIVED_LABEL: 'प्राप्ती दिनांक',
  CERTIFICATE_DATE_RECEIVED_PLACEHOLDER: 'डीडी/मम/वाईवाईवाईवाई',
  CERTIFICATE_UPLOAD_CERTIFICATE_BUTTON: 'प्रमाणपत्र अपलोड करा',
  CERTIFICATE_ADD_OR_EDIT_BUTTON: 'प्रमाणपत्र जोडा / संपादित करा',
  CERTIFICATE_ADDING_CERTIFICATE_BUTTON: 'प्रमाणपत्र जोडत आहे',
  CERTIFICATE_UPLOADING_CERTIFICATE_BUTTON: 'प्रमाणपत्र अपलोड घडत आहे',
  CERTIFICATE_CANCEL_BUTTON: 'रद्द करा',
  CERTIFICATE_TABLE_CERTIFICATE_NAME_HEADING: 'प्रमाणपत्र नाव',
  CERTIFICATE_TABLE_AVARDED_BY_HEADING: 'द्वारा पुरस्कृत',
  CERTIFICATE_TABLE_RECEIVED_DATE_HEADING: 'प्राप्ती दिनांक',
  CERTIFICATE_VIEW_BUTTON: 'प्रमाणपत्र पहा',
  CERTIFICATE_TABLE_INFO: 'संपादित करण्यासाठी प्रमाणपत्र नावावर क्लिक करा',
  // const for /user/certificates page ends
  // const for /passwordchange page *ts
  CHANGE_PASSWORD_HEADING: 'पासवर्ड बदला',
  CHANGE_PASSWORD_OLD_PASSWORD_LABEL: 'जुना पासवर्ड',
  CHANGE_PASSWORD_OLD_PASSWORD_PLACEHOLDER: 'जुना पासवर्ड',
  CHANGE_PASSWORD_NEW_PASSWORD_LABEL: 'नवीन पासवर्ड',
  CHANGE_PASSWORD_NEW_PASSWORD_PLACEHOLDER: 'नवीन पासवर्ड',
  CHANGE_PASSWORD_CONFIRM_PASSWORD_LABEL: 'पासवर्डची पुष्टी करा',
  CHANGE_PASSWORD_CONFIRM_PASSWORD_PLACEHOLDER: 'पासवर्डची पुष्टी करा',
  CHANGE_PASSWORD_SUBMIT_BUTTON: 'सबमिट करा',
  // const for /passwordchange page ends

  // Edit user and upload user data
  EMAIL: 'ईमेल',
  SITES: 'ब्लॉक्स',
  COURSES: 'अभ्यासक्रम',
  SERCH_FOR_COURSE: 'अभ्यासक्रम शोधा',
  UPLOAD_USER_DATA: 'विद्यार्थ्याचे डेटा अपलोड करा',
  CENTER: 'ब्लॉक',
  SELECT_CENTER: 'ब्लॉक निवडा',
  ASYNC_FIELD: 'अतुल्यकालिक फील्ड',
  FILE_NAME: 'फाईलचे नाव',
  FILE_SELECTION: 'फाइल निवड',
  DOWNLOAD_EXCEL_TEMPLATE: 'एक्सेल टेम्पलेट डाउनलोड करा',
  UPLOAD_DIRTY_MSG: ' आवश्यक आहे.',
  UPLOAD_FILE: 'फाइल अपलोड करा',
  SEAT_AVAILABLE: 'आसन उपलब्ध',
  STUDENT_SELECTED: 'निवडलेले विद्यार्थी',
  STUDENT: 'विद्यार्थी',
  CREATE_USER: 'विद्यार्थ्याचे खाते तयार करा',
  EDIT_USER_ACCOUNT: 'विद्यार्थ्याचे खाते संपादित करा',
  SELECT_FILE: 'फाइल निवडा',
  LEARNER_DETAILS: 'विद्यार्थ्याचे तपशील',
  LICENSE_NUMBER: 'परवाना क्रमांक',
  ENRROLLED_END_DATE: 'परवाना समाप्ती तारीख',
  LICENSE_STATUS: 'परवाना स्थिती',
  ENROLLED_DATE: 'नामांकित तारीख',
  SEARCH_COURSES: 'अभ्यासक्रम शोधा',
  CREATE_USER_ACCOUNT: 'वैयक्तिक विद्यार्थ्याचे खाते तयार करा',
  ENROLLED_TO_OTHER_ORG_SUBTITLE_MSG: 'टीप: कृपया खाली सूचीबद्ध केलेल्या इतर ईमेल आयडीसह नोंदणी करा',
  UNABLE_TO_UPLOAD_BULK_USER_FILE: 'फाइल अपलोड करण्यास अक्षम .कृपया वैध फाइल स्वरूप निवडा',
  USER_ENROLLED_TO_COURSE_SUBTITLE_MSG: 'टीप: कृपया नोंदणीसह पुढे जाण्यासाठी खाली सूचीबद्ध वापरकर्त्यास काढा',
  INSUFFICIENT_LICENSE_SUBTITLE_MSG:
    'टीप: कृपया उपलब्ध असलेल्या सीट्सच्या वैध संख्येसह कोर्स निवडा किंवा काही विद्यार्थ्यांना काढा',
  UPLOAD_LEARNERS: 'अपलोड शिकणारे',


  // Create Site
  CREATE_ORGANISATION_CENTER: 'संस्था ब्लॉक तयार करा',
  EDIT_ORGANISATION_CENTER: 'संस्था ब्लॉक संपादित करा',
  CENTER_NAME: 'ब्लॉक नाव',
  CITY: 'शहर',
  CENTER_ADMINS: 'ब्लॉक प्रशासक',
  SELECT_ADMIN: 'प्रशासक निवडा',
  CREATE_CENTER: 'ब्लॉक तयार करा',
  BASIC_INFORMATION: 'मुलभूत माहिती',
  MY_INFO: 'माझी माहिती',
  MOBILE_NO: 'मोबाइल नंबर ',
  GENDER: 'लिंग',
  DOB: 'जन्मतारीख',
  ADDRESS: 'पत्ता',
  MARITAL_STATUS: 'वैवाहिक स्थिती',
  ADDRESS_LINE_1: 'पत्ता ओळ 1',
  ADDRESS_LINE_2: 'पत्ता ओळ 2',
  ENTER_ADDRESS_LINE_1: 'पत्ता ओळ 1 प्रविष्ट करा',
  ENTER_ADDRESS_LINE_2: 'पत्ता ओळ 2 प्रविष्ट करा',
  ENTER_CITY: 'शहर प्रविष्ट करा',
  STATE: 'राज्य',
  ENTER_STATE: 'राज्य प्रविष्ट करा',
  COUNTRY: 'देश',
  ENTER_COUNTRY: 'देश प्रविष्ट करा',
  PINCODE: 'पिन कोड',
  ENTER_PINCODE: 'पिन कोड प्रविष्ट करा',

  // for forgot password localization
  RESET_PASSWORD: 'पासवर्ड रीसेट करा',
  EMAIL_ADDRESS: 'ई-मेल पत्ता',
  OR: 'किंवा',
  TEMPORARY_PASSWORD_MSG: 'आपण आपला तात्पुरता संकेतशब्द कसा प्राप्त करू इच्छिता?',
  SEND: 'पाठवा',
  TEMPORARY_SMS_SUCCESS_MSG:
    'आपल्या तात्पुरत्या पासवर्डासह एक एसएमएस आपल्या प्रोफाइलवरील मोबाइल फोन नंबरवर पाठविला गेला आहे',
  TEMPORARY_MAIL_SUCCESS_MSG: 'आपल्या प्रोफाइलवरील ई-मेल पत्त्यावर तात्पुरता पासवर्ड पाठविला गेला आहे',
  TEMPORARY_LOGIN_MSG: 'आपल्या विद्यार्थी आयडी आणि तात्पुरते पासवर्डसह लॉग इन करा',
  RESEND_TEMPORARY_PASSWORD_LINK: 'तात्पुरता पासवर्ड पुन्हा पाठवा',
  // end forgot password page
  // COURSE OVERVIEW PAGE
  COURSE_OVERVIEW_BY: 'द्वारा',
  COURSE_OVERVIEW_LANGUAGE: 'भाषा',
  COURSE_OVERVIEW_PREVIEW_COURSE: 'पूर्वावलोकन अभ्यासक्रम',
  COURSE_OVERVIEW_TAKE_ASSESSMENT: 'मूल्यांकन घ्या',
  COURSE_OVERVIEW_ENTER_CLASSROOM: 'आपला वर्ग प्रविष्ट करा',
  COURSE_OVERVIEW_VIEW_ALL_COURSE: 'सर्व कोर्स पहा',
  COURSE_OVERVIEW_COURSE_OUTLINE: 'अभ्यासक्रम बाह्यरेखा',
  COURSE_OVERVIEW_OUTCOME: 'परिणाम',
  COURSE_OVERVIEW_LEVEL: 'स्तर',
  COURSE_OVERVIEW_PRE_REQUESTIES: 'पूर्वापेक्षा',
  COURSE_OVERVIEW_DURATION: 'कालावधी',
  COURSE_OVERVIEW_WHO_SHOULD_ATTEND: 'कोण उपस्थित असावे',
  COURSE_OVERVIEW_JOB_ROLE: 'नोकरीची भूमिका',
  COURSE_OVERVIEW_INDUSTRY: 'उद्योग',
  COURSE_OVERVIEW_PRICE: 'किंमत',
  COURSE_OVERVIEW_RESOURCES: 'अभ्यासक्रम संसाधन',
  // END COURSE OVERVIEW
  // CLASSROOM PAGE
  CLASSROOM_OBJECTIVE: 'शिकण्याचे परिणाम्ट',
  CLASSROOM_SEARCH_PLACEHOLDER: 'शोधा ...',
  CLASSROOM_COURSE_DETAILS: 'कोर्स तपशील',
  // END CLASSROOM
  // Roles page(view Roles)
  VIEW_ROLES: 'भूमिका पहा',
  ROLES: 'भूमिका',
  SEARCH_ROLE: 'भूमिका शोधा',
  ROLE_NAME: 'भूमिका नाव',
  ROLE_TYPE: 'भूमिका प्रकार',
  CREATED_ON: 'रोजी तयार केले',
  START_DATE: 'प्रारंभ तारीख *',
  END_DATE: 'शेवटची तारीख *',
  STATUS: 'स्थिती',
  VIEW_ROLE_NAME_INFO: '* संपादित करण्यासाठी भूमिका नावावर क्लिक करा.',
  VIEW_ROLE_DATE_INFO: '* प्रारंभ आणि समाप्ती तारीख केवळ तात्पुरती भूमिकांसाठी आहेत.',
  NO_ROLES_AVAILABLE: 'कोणतीही भूमिका उपलब्ध नाहीत',
  // END View Roles
  // ASSESMENT LOCAlIZATION
  ASSESSMENT_START_TEST: 'चाचणी सुरू करा',
  ASSESSMENT_NO_OF_QUESTION: 'प्रश्नांची संख्या',
  ASSESSMENT_NO_OF_ATTEMPTS: 'प्रयत्नांची संख्या',
  ASSESSMENT_TOTAL_MARKS: 'एकूण गुण',
  ASSESSMENT_PASSING_MARKS: 'पासिंग गुण',
  ASSESSMENT_DURATION: 'कालावधी',
  ASSESSMENT_PREV_QUESTION: 'मागील प्रश्न',
  ASSESSMENT_NEXT_QUESTION: 'पुढचा प्रश्न',
  ASSESSMENT_SUBMIT_TEST: 'चाचणी सबमिट करा',
  ASSESSMENT_SL_NO: 'एस.आय क्रमांक',
  ASSESSMENT_YOUR_SCORE: 'आपला स्कोअर',
  ASSESSMENT_YOUR_MARKS: 'तुमचे गुण',
  ASSESSMENT_DATE: 'तारीख',
  ASSESSMENT_TEST_STATUS: 'स्थिती',
  ASSESSMENT_RESULT: 'निकालपत्रक',
  ASSESSMENT_PASS_MARKS: 'उत्तीर्ण गुण',
  ASSESSMENT_GO_TO_CHAPTER: 'अध्याय वर जा',
  ASSESSMENT_RETEST: 'पुन्हा चाचणी',
  ASSESSMENT_GO_TO_CERTIFICATES: 'माझ्या प्रमाणपत्रांवर जा',
  ASSESSMENT_CONFIRM_SUBMIT: 'आपण चाचणी सबमिट करू इच्छिता',
  ASSESSMENT_ANSWER_ALL: 'चाचणी सबमिट करण्यापूर्वी सर्व प्रश्नांची उत्तरे द्या',
  ASSESSMENT_SUBMIT_TITLE: 'चाचणी सबमिट करा',
  ASSESSMENT_SUBMIT_BUTTON: 'सबमिट करा',
  ASSESSMENT_PASS: 'आपण हा धडा यशस्वीरित्या पूर्ण केला आहे.',
  ASSESSMENT_CERTIFICATE_PASS: 'आपण यशस्वीरित्या हा कोर्स पूर्ण केला आहे.',
  ASSESSMENT_FAIL: 'कृपया धडा पुन्हा काळजीपूर्वक अभ्यास करा.',
  ASSESSMENT_FINAL_FAIL: 'खालील अध्याय पुन्हा काळजीपूर्वक अभ्यास करा.',
  ASSESSMENT_RECOMMENDATION: ' आपण चांगले गुण मिळविण्यासाठी खालील अध्यायांचे अभ्यास करू शकता.',
  ASSESSMENT_SELECT_ANSWER: 'एक उत्तर निवडा',
  ASSESSMENT_LABEL_PASS: 'पास',
  ASSESSMENT_LABEL_FAIL: 'अपयशी',
  ASSESSMENT_GRADE: 'ग्रेड',
  // END ASSESSMENT
  // Forum Page
  CATEGORIES: 'श्रेण्या',
  SEARCH_CATEGORIES_LABEL: 'श्रेण्यां शोधा',
  SEARCH_TOPICS_LABEL: 'विषय शोधा',
  TOPICS: 'विषय',
  CATEGORY_SELECT_LABEL: 'कृपया एक श्रेणी निवडा',
  POST: 'पोस्ट्स',
  TOPIC_SELECT_LABEL: 'कृपया एक विषय निवडा',
  NO_CATEGORIES_LABEL: 'कोणतीही श्रेण्या सापडली नाहीत',
  NO_TOPICS_LABEL: 'श्रेण्या नाहीत',
  SEARCH_POSTS: 'निवडलेल्या विषयामध्ये शोधा',
  SORT_BY_LABEL: 'क्रमवारी लावा',
  RECENT_LABEL: 'अलीकडील',
  NO_POSTS_LABEL: 'कोणतीही पोस्ट नाहीत',
  START_DISCUSSION_LABEL: 'नवीन चर्चा सुरू करा',
  TRENDING_DISCUSSION_LABEL: 'ट्रेन्डिंग चर्चा',
  NO_DICUSSION_LABEL: 'ट्रेन्डिंग चर्चा सापडली नाहीत',
  LOGIN_TO_VOTE: 'मतदान करण्यासाठी कृपया लॉग इन करा.',
  LOGIN_TO_COMMENT: 'टिप्पणी करण्यासाठी कृपया लॉग इन करा.',
  LOGIN_TO_POST: 'चर्चा पोस्ट करण्यासाठी कृपया लॉग इन करा.',
  // Role Default
  ORGANIZATION_ROLE_OVERVIEW_LABEL: 'संस्था भूमिका आढावा',
  ORGANIZATION_NAME_LABEL: 'संस्थेचे नाव',
  NO_OF_ROLES_LABEL: 'भूमिकांची संख्या',
  // Login page
  FORGOT_PASSWORD: 'पासवर्ड विसरला?',
  USERNAME_PLACEHOLDER: 'लॉगिन आयडी / ईमेल पत्ता',
  INVALID_CREDENTIALS: 'अवैध प्रमाणपत्रे',
  // Course catalog page
  VIEW_ALL_COURSES_LINK: 'सर्व अभ्यासक्रम पहा',
  VIEW_ALL_CATEGORIES_LINK: 'सर्व श्रेण्या पहा',
  PARTICIPATE_IN_DISCUSSION_LINK: 'चर्चा मध्ये सहभागी व्हा',
  COURSE_CAROUSEL_WHAT_WOULD_YOU_LIKE_TO: 'तुम्हाला काय करायला आवडेल',
  COURSE_CAROUSEL_TODAY: 'आज?',
  HOST_TYPE_VOCATIONAL_DESCRIPTION: `एक अद्वितीय स्थानिकीकृत तंत्रज्ञान कंपनी जी अभियांत्रिकी आणि उत्पादन माहितीला मिश्रण करते
  स्व-निर्देशित, डिजिटल संवादात्मक उत्पादने विकसित करा, वास्तविक जीवन अनुभवांचे अनुकरण करा. ज्ञान पोडियम
  उपभोग, संस्थात्मकरण, वितरणासाठी आणि उपभोग आश्वासन देण्यासाठी व्यापक आणि साध्या उत्पादनांची निर्मिती करते
  संस्थेच्या ज्ञान त्याच्या मूल्य-साखळीत. संस्थेने यशस्वीरित्या उत्पादने तयार केली आहेत
  अभियांत्रिकी, उत्पादन, कौशल्य उन्नतीकरण आणि मुख्य उद्योग आणि मोठ्या उद्योगांची ज्ञान धारणा आवश्यकता
  भारतातील आणि परदेशात शैक्षणिक संस्था.`,
  HOST_TYPE_TEACHERS_DESCRIPTION: `आम्ही रुपांतरणात विश्वास ठेवतो आणि म्हणून प्रवेश करून कोणालाही, कोणालाही संधी प्रदान करतो
  जगातील सर्वोत्तम शिक्षण अनुभव. आपण अभ्यासक्रमांची सूचीमधून निवड करू शकता, जो आपल्याला विशिष्टता मिळविण्यात मदत करतो
  व्याज क्षेत्रात. म्हणून आपली वेळ आणि स्थान आव्हाने अदृश्य होऊ दे आणि आपण आपली शिकण्याची प्रवासा पुढे नेऊ.
  आज आपण काय शिकू इच्छिता ते निवडा.`,
  COURSE_CAROUSEL_LEARN: ' जाणून घ्या ',
  // Footer
  CONTACT: 'संपर्क',
  QUICK_LINKS: 'जलद दुवे',
  ABOUT_US: 'आमच्याबद्दल',
  TERMS_OF_USE: 'वापरण्याच्या अटी',
  PRIVACY_POLICY: 'गोपनीयता धोरण',
  CONTACT_US: 'आमच्याशी संपर्क साधा',
  FAQ: 'सामान्य प्रश्न',
  HOW_TO: 'कसे?',
  HAVE_A_QUESTION: 'एक प्रश्न आहे?',
  LEAVE_A_REPLY_MESSAGE: 'खाली आपला ईमेल आयडी सोडा. आम्ही आपल्याशी संपर्क साधू.',
  EMAIL_PLACEHOLDER: 'ईमेल आयडी प्रविष्ट करा',
  SELECT_LANGUAGE: 'भाषा निवडा',

  // Roles
  ROLE_START_DATE_LABEL: 'भूमिका प्रारंभ तारीख (जर अस्थायी असेल तर.)',
  ROLE_END_DATE_LABEL: 'भूमिका शेवटची तारीख (जर अस्थायी असेल तर.)',
  NEXT: 'मागोमागचा',
  DELETE: 'खोडून टाकणे',
  DELETE_ROLE: 'भूमिका हटवा',
  ROLE_NAME_PLACEHOLDER: 'भूमिका नाव प्रविष्ट करा',
  ROLE_TYPE_PLACEHOLDER: 'भूमिका प्रकार निवडा',
  CREATE_ROLE_LABEL: 'भूमिका तयार करा',
  EDIT_RESPONSIBILITIES_LABEL: 'जबाबदारी संपादित करा',
  ROLE_DELETE_ALERT_LABEL: 'आपणास खात्री आहे की आपण ही भूमिका हटवू इच्छिता?',
  ROLE_IN_USER_LABEL: 'भूमिका वापरात आहे .कृपया खालील प्रशासकांसाठी भूमिका बदला आणि पुन्हा प्रयत्न करा .',
  EDIT_ROLE: 'भूमिका संपादित करा',
  REGULAR_LABEL: 'नियमित',
  TEMPORARY_LABEL: 'तात्पुरता',
  //  Admin Licesne Page Labels
  ADMIN_LICENSE_LABEL_LICENSES: 'परवाने',
  ADMIN_LICENSE_SEARCH_LICENSE_PLACE_HOLDER: 'कोर्स परवान्यासाठी शोध',
  ADMIN_LICENSE_LICENSE_ID: 'परवाना आयडी',
  ADMIN_LICENSE_COURSE_PRODUCT_NAME: 'कोर्स / उत्पादन नाव',
  ADMIN_LICENSE_PURCHASE_DATE: 'खरेदी दिनांक',
  ADMIN_LICENSE_QUANTITY: 'संख्या',
  ADMIN_LICENSE_LICENSE_REMAINING: 'शेष परवाने',
  ADMIN_LICENSE_STATUS: 'स्थिती',
  ADMIN_LICENSE_LICENESE_VIEW_NOTE: '* परवाना तपशील पाहण्यासाठी कोर्सच्या नावावर क्लिक करा',
  //  Admin License Details Page Labels
  ADMIN_LICENSE_DETAILS_LABEL_LICENSE_DETAILS: 'परवाना तपशील',
  ADMIN_LICENSE_DETAILS_PRODUCT_NAME: 'उत्पादनाचे नांव',
  ADMIN_LICENSE_DETAILS_REQUEST_DATE: 'विनंती केलेली तारीख',
  ADMIN_LICENSE_DETAILS_START_DATE: 'प्रारंभ तारीख',
  ADMIN_LICENSE_DETAILS_END_DATE: 'शेवटची तारीख',
  ADMIN_LICENSE_DETAILS_LICENSE_PURCHASED: 'खरेदी परवाना',
  ADMIN_LICENSE_DETAILS_LICENSE_USED: 'वापरलेले परवाना',
  ADMIN_LICENSE_DETAILS_REQUEST_MORE_LICENSE_LABEL: 'अधिक परवान्याची विनंती करा',
  ADMIN_LICENSE_DETAILS_SEARCH_ADMIN: 'प्रशासक शोधा',
  ADMIN_LICENSE_DETAILS_ADMIN_LICENSE_USER_NAME: 'विद्यार्थ्याचे नाव',
  ADMIN_LICENSE_DETAILS_USER_EMAIL_ID: 'लिअरर ईमेल आयडी',
  ADMIN_LICENSE_DETAILS_ENROLLED_DATE: 'नामांकित तारीख',
  ADMIN_LICENSE_DETAILS_USER_PROGRESS: 'प्रगती',

  // Dashboard
  DASHBOARD_RECENTLY_VIEWED: 'नुकतेच पाहिलेले',
  DASHBOARD_MY_COURSES: 'माझे कोर्स',
  DASHBOARD_RECOMMENDED_COURSES: 'शिफारस केलेले कोर्स',
  DASHBOARD_COURSES_PROGRESS: 'प्रगती',
  DASHBOARD_CREATED_BY: 'ने निर्मित',
  DASHBOARD_POD: 'POD:',
  VIEW_ALL: 'सर्व पहा',
  TAKE_ASSESSMENT: 'मूल्यांकन घ्या',
  ENTER_CLASSROOM: 'आपला वर्ग प्रविष्ट करा',
  PREVIEW_COURSE: 'पूर्वावलोकन',
  NO_SUBSCRIPTION: 'प्रदर्शित करण्यासाठी कोणतेही वर्तमान सदस्यता नाहीत',
  CURRENT_SUBSCRIPTION: 'वर्तमान सदस्यता',
  COURSE_NAME: 'कोर्सचे नाव',
  COURSE_PROGRESS: 'कोर्सचे प्रगती',
  SUBSCRIPTION_LEFT: 'सदस्यता दिवस बाकी',
  NO_PAST_SUBSCRIPTION: 'प्रदर्शित करण्यासाठी मागील सदस्यता नाहीत',
  PAST_SUBSCRIPTION: 'मागील सदस्यता',
  EXPIRED_DATE: 'कालबाह्य तारीख',
  NOT_PERMITTED: 'परवानगी नाही.',
  COURSE_LEVEL: 'कोर्स पातळी ',
  // discussion
  DISCUSSION_FORUMS_FIELD: 'मंच *',
  DISCUSSION_FORUM_LABEL: 'फोरम नाव टाइप करा',
  DISCUSSION_TOPIC_FIELD: 'विषय निवडा *',
  DISCUSSION_TOPIC_LABEL: 'टाइप टॉपिक नाव',
  DISCUSSION_LEVEL_FIELD: 'आपल्या विषयाची "स्तर" सर्वोत्तम काय परिभाषित करते?*',
  DISCUSSION_TITLE_FIELD: 'शीर्षक *',
  DISCUSSION_TITLE_LABEL: 'येथे शीर्षक प्रविष्ट करा',
  DISCUSSION_DESCRIPTION_FIELD: 'येथे आपले पोस्ट / टिप्पणी द्या *',
  DISCUSSION_REQUIRED: 'वर्णन * आवश्यक आहे.',
  POST_DISCUSSION: 'चर्चा पोस्ट करा',
  PREVIEW_DISCUSSION: 'पूर्वावलोकन',
  EDIT_DISCUSSION: 'संपादित करा',
  DISCUSSION_POST: 'पोस्ट',
  // REQUIRED_COMMENT: 'टिप्पणी आवश्यक आहे.',
  REPLY_COMMENT: 'उत्तर द्या',
  COMMENT_FLAG: 'ध्वज',
  DISCUSSION_COMMENTS: 'टिप्पण्या',
  ADD_COMMENT: 'टिप्पण्या जोडा',

  // OrgAdminRequests
  REQUEST_TYPE: 'विनंती प्रकार *',
  REQUEST_DETAILS: 'विनंती तपशील *',
  SELECT_REQUEST_TYPE: 'विनंती प्रकार निवडा',
  SEARCH_COURSE: 'अभ्यासक्रम शोधा',
  REQUEST_DETAILS_PLACEHOLDER:
    'आपल्या विनंतीचे थोडक्यात वर्णन करा आणि आमच्या ग्राहक प्रतिनिधींपैकी एक 24 तासांच्या आत उत्तर देईल.',
  ORG_ADMIN_REQUESTS_SUBMIT: 'सबमिट करा',
  ORG_ADMIN_REQUESTS_HEADING: 'कृपया आम्हाला सांगा की आम्ही आपली मदत कशी करू शकतो',
  ORG_ADMIN_REQUESTS_SUBHEADING: '* तांत्रिक समस्यांसह त्वरित मदतीसाठी कृपया आमच्या विक्री प्रतिनिधीस कॉल करा.',
  // My Certificate
  MYCERTIFICATE_HEADING: 'माझी प्रमाणपत्रे',
  NO_CERTIFICATE: 'कोणतेही प्रमाणपत्र सापडले नाहीत .',
  VIEW_CERTIFICATE: 'प्रमाणपत्र पहा',
  // Modal
  MODAL_OK: 'ठीक आहे',
  MODAL_CANCEL: 'रद्द करा',
  // End Modal

  // view Users
  NUMBER_OF_ENROLLED_PODS: 'नामांकित फोडांची संख्या',
  NUMBER_OF_COMPLETED_PODS: 'पूर्ण केलेल्या फोडांची संख्या',
  CLICK_ON_USER_NAME_TO_EDIT: 'संपादित करण्यासाठी विद्यार्थ्याच्या नावावर क्लिक करा',
  SEARCH_USERS: 'विद्यार्थी शोधा',
  LEARNER_NAME: 'विद्यार्थ्याचे नाव',
  APPROVE_LEARNER_CONFIRMATION: 'क्या आप वाकई शिक्षार्थी को अनुमोदित करना चाहते हैं?',
  APPROVE_LEARNER_CONFIRMATION_TITLE: 'शिक्षार्थी की पुष्टि',
  REJECT_LEARNER_CONFIRMATION: 'आपण शिक्षणाची विनंती नाकारू इच्छित असल्याची आपल्याला खात्री आहे?',
  REJECT_LEARNER_CONFIRMATION_TITLE: 'शिक्षार्थी विनंती नाकारू',

  DELETE_LEARNER_CONFIRMATION: 'आपणास शिक्षार्थी आहे की आपण विद्यार्थ्याला हटवू इच्छिता?',
  DELETE_LEARNER_CONFIRMATION_TITLE: 'शिक्षार्थी हटवा',

  // <-- url: /admin/detail,  Admin Detail page localization *t -->
  ADMIN_ACCOUNT_DETAILS: 'प्रशासक खाते तपशील',
  ORGASNISATION_NAME: 'संस्थेचे नाव',
  ADMIN_FIRST_NAME: 'प्रशासक प्रथम नाव',
  ADMIN_LAST_NAME: 'प्रशासक शेवटचे नाव',
  ADMIN_EAIL_ID: 'प्रशासक ईमेल आयडी',
  ADMIN_MOBILE_NO: 'प्रशासक मोबाइल नंबर',
  ADMIN_CONTACT_US_PLEASE: 'कृपया',
  ADMIN_CONTACT_US_UPDATE: 'खाते तपशील सुधारित किंवा अद्ययावत करण्यासाठी',
  ADMIN_CONTACT_US: 'आमच्याशी संपर्क साधा',

  // <-- url: /admin/detail,  Admin Detail page localization end -->
  // Admin home screen welcme message
  ADMIN_ROUTEPAGE_WELCOME: 'स्वागत आहे',
  ADMIN_ROUTEPAGE_ADMINISTRATOR: 'प्रशासक',
  SEE_COURSE_DETAILS: 'कोर्स तपशील पहा',

  MY_COURSES: 'माझे कोर्स',
  SORT_BY: 'क्रमवारी लावा',
  NO_RECORDS_FOUND: 'कोणतेही रेकॉर्ड आढळले नाहीत',
  // EDUCATION_QUALIFICATIONS
  EDUCATION_QUALIFICATIONS: 'शैक्षणिक पात्रता',
  LEVEL_OF_EDUCATION: 'शिक्षणाचा स्तर',
  INSTITUTION_NAME: 'संस्थेचे नाव',
  FIELD_OF_STUDY: 'अभ्यासाचे क्षेत्र',
  PERCENTAGE: 'टक्केवारी',
  YEAR_OF_GRADUATION: 'पदवी वर्ष',
  CURRENTLY_PURSUING: 'सध्या पाठपुरावा करत आहे',
  SELECT_EDUCATION: 'शिक्षण निवडा',
  SAVE_EDUCATION: 'शिक्षण जतन करा',
  ADD_EDUCATION: 'शिक्षण जोडा',
  NAME_OF_THE_INSTITUTION: 'संस्थेचे नाव',
  EDUCATION_DELETE_ALERT_LABEL: 'आपणास खात्री आहे की आपण ही शिक्षण हटवू इच्छिता?',
  DELETE_EDUCATION_CONFIRMATION: 'शिक्षण पुष्टीकरण हटवा',

  RECOMMENDED_COURSES: 'शिफारस केलेले कोर्स',
  WORK_EXPERIENCE: 'कामाचा अनुभव',
  DELETE_WORK_EXPERIENCE_CONFIRMATION: 'कार्य अनुभव पुष्टीकरण हटवा',
  WORK_EXPERIENCE_DELETE_ALERT_LABEL: 'आपणास खात्री आहे की आपण हा कार्य अनुभव हटवू इच्छित आहात?',
  JOB_TITLE: 'जॉब शीर्षक *',
  ORG: 'संस्था *',
  START_MONTH: 'प्रथम महिना',
  START_YEAR: 'प्रथम वर्ष',
  END_MONTH: 'समाप्ती महिना',
  END_YEAR: 'समाप्ती वर्ष',
  CURRENTLY_WORKING: 'सध्या कार्यरत आहे',
  JOB_DESC: 'कामाचे स्वरूप',
  TO: 'च्याकडे',
  ENTER_JOB_TITLE: 'जॉब शीर्षक प्रविष्ट करा',
  ENTER_ORG_NAME: 'संस्थेचे नाव प्रविष्ट करा',
  MONTH: 'महिना',
  YEAR: 'वर्ष',
  JOB_RESP_ACHIVEMENTS: 'जॉब जबाबदार्या आणि यशांची यादी करा',
  ADD_JOB: 'जॉब जोडा',
  UPDATE_JOB: 'जॉब अपडेट करा',
  MY_SKILLS: 'माझी कौशल्यं',
  SKILLS: 'कौशल्ये',
  SKILL: 'कौशल्य',
  YEARS: 'वर्षे',
  EXPERIENCE: 'अनुभव',
  MONTHS: 'महिने',
  UPDATE_SKILL: 'अद्यतन कौशल्य',
  ADD_SKILL: 'कौशल्य जोडा',
  TYPE_SKILL_NAME: 'कौशल्य नाव टाइप करा',
  // Recommended Courses
  RECOMMENDED_CHAPTER_NAME: 'धडा',
  RECOMMENDED_WRONG_ANSWER_COUNT: 'चुकीच्या उत्तरेंची संख्या',

  // user inbox constants
  NO_RESULTS_TO_SHOW: 'दर्शविण्यासाठी आणखी काही परिणाम नाहीत ..',
  NO_CONVERSATIONS: 'प्रदर्शित करण्यासाठी कोणतेही संभाषण .',
  NO_ACTIVE_CONVERSATION: 'प्रदर्शित करण्यासाठी सक्रिय संभाषण नाही .',
  CREATE_CONVERSATION: 'नवीन संभाषण सुरू करा',
  DELETE_CONVERSATION: 'निवडलेले संभाषण हटवा',
  ADD_CONNECTION: 'कनेक्शन जोडा',
  BLOCK_CONNECTION: 'कनेक्शन ब्लॉक करा',
  UNBLOCK_CONNECTION: 'कनेक्शन अनब्लॉक करा',
  CONVERSATION_DELETE_ALERT_LABEL: 'आपण निवडलेले संभाषण हटवू इच्छित असल्याची आपल्याला खात्री आहे?',
  DELETE_CONVERSATION_LABEL: 'निवडलेले संभाषण पुष्टीकरण हटवा',
  SEARCH_CONNECTION_LABEL: 'कनेक्शन शोधा',
  CONNECT_LABEL: 'कनेक्ट करा',
  NO_PREVIOUS_CONVERSATION: 'प्रदर्शित करण्यासाठी मागील संभाषण नाही',
  TYPE_NAME: 'नाव टाइप करा',
  ADD_CONNECTION_PLACEHOLDER: 'आपण जोडू इच्छित असलेल्या वापरकर्त्याचे ईमेल आयडी प्रविष्ट करा',
  DELETE_USER: 'वापरकर्ता हटवा',
  ACCEPT_INVITATION_LABEL: 'आमंत्रण स्वीकारा',
  REJECT_LABEL: 'नाकार',
  PENDING_INVITATION_COUNT: 'प्रलंबित निमंत्रण संख्या',
  SEND_ADD_REQUEST_LABEL: 'जोडा विनंती पाठवा',
  DENY_LABEL: 'नाकारू',

  // verify email
  PROCEED_BUTTON: 'पुढे जा',
  RESEND_BUTTON: 'पुन्हा पाठवा',
  VERIFY_EMAIL_LINK_SUCCESS_MSG:
    'अभिनंदन, आपले ईमेल यशस्वीरित्या सत्यापित केले गेले आहे कृपया लॉगिन करण्यासाठी खाली क्लिक करा',
  VERIFY_EMAIL_LINK_FAILURE_MSG: 'क्षमस्व, आपला दुवा कालबाह्य झाला आहे. दुवा पुन्हा पाठवण्यासाठी कृपया खाली क्लिक करा',
  // end of verify email
  ACCEPT_LABEL: 'मंजूर',
  DELETE_LABEL: 'हटवा',

  // Delete Certificate confirmation
  DELETE_CERTIFICATE_CONFIRMATION: 'आपणास खात्री आहे की आपण हे प्रमाणपत्र हटवू इच्छिता?',
  DELETE_CONFIRMATION_TITLE: 'प्रमाणपत्र पुष्टीकरण हटवा',

  SHOW_ADD_COMMENT_ERROR: 'टिप्पणी आवश्यक .',
  LOOKING_FOR: 'आपणास काय हवे आहे ?',
  REFINE_SEARCH: 'शोध परिष्कृत करा',
  RESET: 'रीसेट करा',
  INDUSTRY: 'उद्योग',
  TYPE: 'टाइप करा',
  SKILL_LEVEL: 'कौशल्य पातळी',
  SELECT: 'निवडा',
  END_RESULT: 'परिणाम संप',
  VIEW: 'पहा',
  COURSES_CATALOG: 'कोर्स कॅटलॉग',
  COURSE_DURATION: 'कोर्स कालावधी:',
  LEARN_MORE: 'अधिक जाणून घ्या',
  DELETE_SKILL_CONFIRMATION: 'आपणास खात्री आहे की आपण ही कौशल्य हटवू इच्छिता ?',
  DELETE_TITLE_SKILL_CONFIRMATION: 'कौशल्य पुष्टीकरण हटवा',
  ENTER_CLASSROOM_EXPIRES:
    'पॉड परवाना कालबाह्य झाला आहे. वर्ग प्रविष्ट करण्यासाठी कृपया परवान्याची नूतनीकरण करा / परवान्याची नूतनीकरणासाठी आपल्या प्रशासकाशी संपर्क साधा',
  ENTER_CLASSROOM_RECOMMENDED: 'आपण पॉड विकत न घेता फक्त 2 दुवे पाहू शकता',
  MAX_LENGTH_EXCEEDED: 'कमाल लांबी वाढली !!',
  // Reports
  REPORT_PAGE_TITLE: 'अहवाल',
  REPORT_SEARCH_LABEL: 'राज्य, जिल्हा, ब्लॉक, शाळा किंवा विद्यार्थ्यांसाठी उपलब्ध अहवाल मिळवा',
  REPORT_SEARCH_PLACEHOLDER: 'जिल्हा, ब्लॉक, शाळा किंवा विद्यार्थी नाव प्रविष्ट करा',
  REPORT_ALL_DISTRICTS: 'सर्व जिल्हे',
  REPORT_ALL_BLOCKS: 'सर्व विभाग',
  REPORT_ALL_SCHOOLS: 'सर्व शाळा',
  REPORT_SUMMARY_TITLE: 'शिक्षक प्रशिक्षण कार्यक्रम सारांश',
  REPORT_DOWNLOAD_LABEL: 'सारांश डाउनलोड करा',
  REPORT_TOTAL_LEARNERS_LABEL: 'एकूण शिकणारे',
  REPORT_ACTIVE_COURSES_LABEL: 'सक्रिय अभ्यासक्रम',
  REPORT_ACTIVE_ENROLLMENTS_LABEL: 'सक्रिय नोंदणी',
  REPORT_COURSES_INPROGRESS_LABEL: 'एकूण प्रगती अभ्यासक्रम',
  REPORT_CERTIFICATE_AWARDED_LABEL: 'प्रमाणपत्र दिले',
  REPORT_STATISTICS_AND_ANALYTICS_LABEL: 'आकडेवारी आणि विश्लेषण',
  REPORT_TOTAL_COURSES_LABEL: 'एकूण अभ्यासक्रम',
  REPORT_TOTAL_STUDENT_LABEL: 'एकूण शिकणारे',
  REPORT_INPROGRESS_LABEL: 'प्रगतीपथावर',
  REPORT_YET_TO_START_LABEL: 'अद्याप सुरू',
  REPORT_COMPLETED_LABEL: 'पूर्ण',
  REPORT_ENROLLED_LABEL: 'सक्रिय',
  REPORT_INACTIVE_LABEL: 'निष्क्रिय',
  REPORT_CERTIFICATE_AWARDED_TITLE: 'प्रमाणपत्र विरुद्ध अभ्यासक्रम पुरस्कृत',
  REPORT_STUDENT_VS_COURSES_TITLE: 'शिकणारे बनाम उपलब्ध अभ्यासक्रम',
  REPORT_DISTRICTS_DIRECTORY_LABEL: 'जिल्हा निर्देशिका',
  REPORT_STATE_LABEL: 'राज्य:',
  REPORT_KARNATAKA: 'कर्नाटक',
  REPORT_VIEW_REPORTS_LABEL: 'अहवाल पहा',
  REPORT_DISTRICT_NAME_HEADING: 'जिल्हा नाव',
  REPORT_BLOCKS_HEADING: 'विभाग',
  REPORT_HEADING: 'अहवाल द्या',
  REPORT_FIND: 'शोधा',
  REPORT_VIEW_ALL: 'सर्व पहा',
  REPORT_BLOCK_NAME_HEADING: 'ब्लॉक नाव',
  REPORT_SCHOOLS_HEADING: 'शाळा',
  REPORT_SCHOOL_NAME_HEADING: 'शाळेचे नाव',
  REPORT_DISTRICT_LEVEL: 'जिल्हा',
  REPORT_BLOCK_LEVEL: 'ब्लॉक',
  REPORT_SCHOOL_LEVEL: 'शाळा',
  // End Reports
  COURSE_RESOURCE: 'संसाधने',
  // Contact
  KP_CONTACTDETAILS_LINE_1: '21, सिडक आयटी पार्क, सहस्त्रधारा',
  KP_CONTACTDETAILS_LINE_2: 'रोड, देहरादून - 248001,',
  KP_CONTACTDETAILS_STATE: 'उत्तराखंड,',
  KP_CONTACTDETAILS_COUNTRY: 'भारत',
  KP_CONTACTDETAILS_PHONE_NUMBER: 'पी: +91 97564 31011',
  KP_CONTACTDETAILS_EMAILID: 'ई: contact@knowledgepodium.com',
  EDIT_PERMISSION_DENIED: 'आपल्याला संपादनाची परवानगी नाही',

  CANCEL_ADD_REQUEST: 'रद्द करा विनंती जोडा',

  // USER BASIC INFO
  SCHOOLDETAILS: 'शाळा माहिती',
  SCHOOL: 'शाळा',
  BLOCK: 'ब्लॉक',
  DISTRICT: 'जिल्हा',

  // ÷SELF_REGISTRATION
  SELF_REGISTRATION: 'वैयक्तिक नोंदणी',
  TEACHERS_TRAINING_SIGN_UP: 'शिक्षक प्रशिक्षण नोंदणी',
  BASIC_INFO_SCHOOL_INFO: 'मूलभूत माहिती आणि शाळा माहिती',
  SIGN_UP: 'साइन अप करा',
  CONTINUE: 'मोबाइल नंबर सत्यापित करा.',
  ACTIVE_USERS: 'सक्रिय वापरकर्ते',
  DELETED_USERS: 'हटविलेले वापरकर्ते',
  PENDING_LIST: 'प्रलंबित यादी',
  SUCCESSFULL_REGISTRATION: 'आपण यशस्वीरित्या नोंदणीकृत आहात!',
  FOLLOW_INSTRUCTIONS: 'ईमेलमधील सूचनांचे अनुसरण करा.',
  // CONTINUE: 'सुरू ठेवा',
  OTP_VERIFY: 'OTP सत्यापित करा',
  BASIC_INFO: 'मुलभूत माहिती',
  FEEDBACK: 'फीडबॅक',
  BEGIN_SURVEY: 'सर्वेक्षण सुरू करा',
  WE_VALUE_YOUR_FEEDBACK: 'आम्ही आपल्या फीडबॅकचे मूल्यवान आहोत',
  DESCRIPTION_FOR_FEEDBACK:
    'कर्नाटक राज्य सरकारला या नवीन शिक्षक प्रशिक्षण कार्यक्रमाबद्दल तुमचा अभिप्राय आवडेल. या सर्वेक्षणाद्वारे ऑफर केलेले आमचे प्लॅटफॉर्म आणि इतर अभ्यासक्रम सुधारण्यात आमची मदत करा.',
  ANSWER: 'उत्तर',
  // grace Period
  GRACE_PERIOD_MESSAGE: 'आपका लाइसेंस समाप्त हो जाएगा',
  DAYS: 'दिनों में. जारी रखने के लिए लाइसेंस को नवीनीकृत करें.',

  // Course Progress Report
  FAILED_TO_FETCH_COURSE_PROCESS: 'कोर्स प्रगती तपशील आणण्यात अयशस्वीी',
  PROGRESS_COMPLETED_LABEL: 'पूर्ण',
  PROGRESS_INCOMPLETE_LABEL: 'अपूर्ण',
  PROGRESS_CHAPTERS_LABEL: 'अध्याय',
  ASSESSMENT_ATTEMPTED: 'वर प्रयत्न केला',
  ASSESSMENT_SCORE: 'धावसंख्या',
  UNWATCHED_VIDEOS: 'न जुळलेले व्हिडिओ',
  COURSE_PROGRESS_REPORT: 'प्रगती',

  DELETE_ROLE_TITLE: 'भूमिका पुष्टीकरण हटवा',

  YOUR_FEEDBACK_IS_IMPORTANT_TO_US: 'आपला अभिप्राय आमच्यासाठी महत्वाचा आहे',
  LEVEL_OF_EDUCATION_PURSUNING: 'आपण कोणत्या पातळीवर शिक्षण घेत आहात?',
  FIRST_STEP: 'Take your first step to getting an',
  EDUCATION_IN_INDIA: 'education in India',
  REGISTRATION: 'नोंदणी',
  ACTIONS: 'क्रिया',
  USER_DELETE_ALERT_LABEL: 'आपणास खात्री आहे की आपण या वापरकर्त्यास हटवू इच्छिता?',

  // My Journal DashBoard
  RJ_MY_JOURNAL: 'माझे रोजनिशी',
  RJ_MY_COURSES: 'माझे अभ्यासक्रम',
  NO_POD_AVAILABLE: 'आपण कोणत्याही कोर्ससाठी सदस्यता घेतली नाही. कृपया आपल्या साइट प्रशासकाशी संपर्क साधा',
  DOWNLOAD_CHAPTER: 'अध्याय डाउनलोड करा',
  DOWNLOAD_ALL: 'सर्व डाउनलोड करा',
  DOWNLOAD_MODULE: 'मॉड्यूल डाउनलोड करा',
  JOURNAL_COMPLETED: 'पूर्ण',
  JOURNAL_RESUME: 'बायोडाटा',
  DOWNLOAD_COURSE: 'कोर्स डाउनलोड करा',
  DOWNLOAD_JOURNALS: 'रोजनिशी डाउनलोड करा',
  RJ_SEARCH_JOURNAL: 'रोजनिशी शोध',
  // End My Journal Dashboard
  POSTS: 'पोस्ट्स',
  FORUMS: 'मंच',
  SEARCH_FORUMS: 'शोध मंच',
  SEARCH_POSTS_NEW: 'पोस्ट्स शोधा',
  LAST_POST: 'शेवटची पोस्ट',
  HOME: 'घर',
  RESUME_NOW: 'रेशीम नौ',
  RESULTS_FOUND: 'परिणाम सापडले',

  // contact us new
  PURPOSE_OF_INQUIRY: 'चौकशीचा उद्देश',
  NAME: 'नाव',
  MOBILE: 'मोबाइल',
  YOUR_MESSAGE: 'तुमचा निरोप',
  SUBMIT: 'सबमिट करा',
  // end of contact us new

  EDIT_ADD_SEND_REQUEST_LABEL: 'संदेश संपादित करा आणि पाठवा',
  SAVE: 'जतन करा',
  REGISTER: 'नोंदणी करा',
};
