export const required = (value) => { return value ? undefined : 'REQUIRED'; };
export const requiredRadio = (value) => { return value ? undefined : ''; };
export const requiredReactSelect = (value) => { return (value.length > 0) ? undefined : 'REQUIRED'; };
export const number = (value) => { return value && Number.isNaN(Number(value)) ? '' : undefined; };
export const otpNumber = (value) => { return value && Number.isNaN(Number(value)) ? 'INVALID_OTP' : undefined; };
export const maxLength = max => (value) => { return value && value.length > max ? ' ' : undefined; };
export const minLength = min => (value) => { return value && value.length < min ? ' ' : undefined; };
export const minLength8 = minLength(8);
export const maxLength15 = maxLength(15);
export const noSpecialCharacterNoNumber = (value) => { return value && !/^[a-zA-Z ]*$/i.test(value) ? 'INVALID_DETAILS' : undefined; };
export const noSpecialCharacter = (value) => { return value && !/^[0-9a-zA-Z ]*$/i.test(value) ? ' ' : undefined; };
export const mobileNumber = (value) => { return value && !/^\d{10}$/i.test(value) ? 'INVALID_MOBILE' : undefined; };
export const email = (value) => { return value && !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(value) ? 'INVALID_EMAIL' : undefined; };
export const userFullName = (value) => { return value && !/^[A-Za-z ]{1}[A-Za-z ]{0,68}[A-Za-z ]{1}$/i.test(value) ? 'INVALID_NAME' : undefined; };
export const password = (value) => { return value && !/^.{6,}$/i.test(value) ? ' ' : undefined; };
export const mobileAndEmail = (value) => { return value && !(/^\d{10}$/i.test(value) || /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(value)) ? ' ' : undefined; };
export const requiredValidName = (value) => { return !value || (value && !/^[a-zA-Z\-_\s]+$/i.test(value)) ? 'REQUIRED' : undefined; };
export const noStartingSpace = (value) => { return value && value.trim() !== '' ? undefined : 'INVALID_SPACE_IN_FIELD'; };
export const lastName = (value) => { return value && !/^[A-Za-z]{1}[A-Za-z ]{0,68}$/i.test(value) ? 'INVALID_NAME' : undefined; };
export const percentage = (value) => { return value && (Number.isNaN(Number(value)) || value <= 0 || value > 100) ? 'IS_INVALID' : undefined; };
export const fullName = (value) => { return value && !/^[a-zA-Z ]+$/i.test(value) ? 'ONLY_APLHABETS_ALLOWED' : undefined; };
export const newPassword = (value) => { return value && !/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()\-_+={}[\]|\\;',./:"<>?~`])[A-Za-z\d!@#$%^&*()\-_+={}[\]|\\;',./:"<>?~`]{8,}$/g.test(value) ? 'INVALID_PASSWORD' : undefined; };
export const requiredCheckBox = (value) => { return value ? undefined : ' '; };
export const validEmail = (value) => { return value && !/^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i.test(value) ? ' ' : undefined; };
export const validMobileNumber = (value) => { return value && !/^\d{10}$/i.test(value) ? ' ' : undefined; };
export const validUserFullName = (value) => { return value && !/^[A-Za-z ]{1}[A-Za-z ]{0,68}[A-Za-z ]{1}$/i.test(value) ? ' ' : undefined; };
export const ValidLastName = (value) => { return value && !/^[A-Za-z]{1}[A-Za-z ]{0,68}$/i.test(value) ? ' ' : undefined; };
export const validNoStartingSpace = (value) => { return value && value.trim() !== '' ? undefined : ' '; };
export const noAfterTextSpace = (value) => { return value && /\s/g.test(value) ? 'INVALID_AFTER_SPACE_IN_FIELD' : undefined; };
